captive-portal/hier/usr/lib/python2.7/tests/captive_portal_tests.py
captive-portal/hier/usr/share/untangle/web/webui/script/untangle-node-captive-portal/settings.js
captive-portal/src/com/untangle/node/captive_portal/CaptivePortalApp.java
captive-portal/src/com/untangle/node/captive_portal/CaptivePortalSettings.java
captive-portal/src/com/untangle/node/captive_portal/CaptivePortalTimer.java
captive-portal/src/com/untangle/node/captive_portal/CaptivePortalUserCookieTable.java
captive-portal/src/com/untangle/node/captive_portal/CaptivePortalUserEntry.java
captive-portal/src/com/untangle/node/captive_portal/CaptivePortalUserEvent.java
captive-portal/src/com/untangle/node/captive_portal/CaptivePortalUserTable.java
uvm/api/com/untangle/uvm/HostTable.java
uvm/impl/com/untangle/uvm/HostTableImpl.java

This branch includes changes to track captive portal users by MAC address. The feature is disabled by default (legacy behavior) but can be enabled by turning on the corresponding checkbox in settings on the Authentication tab. 
When enabled, the application will attempt to index and track authenticated users based on the MAC address. If no MAC address is available for a user, they will be tracked by IP address.

Ngfw 10097 capture prikey

---

uvm/hier/usr/share/untangle/conf/untangle-vm.conf
uvm/impl/com/untangle/uvm/MetricManagerImpl.java

These patches add recognition of ARM64 CPUs, i.e set the JVM options.
Since /proc/cpuinfo does provide a human readable processor name on arm I've added detection for the Cortex-A53, it should be possible to add other cores (A7, A72 etc.) and/or the SoC as well.
This is enough to build and boot and configure Untangle, there is still a crash issue with nfq_get_ct_info that needs to be fixed before it is fully usable.

ARM64 CPU detection for uvm

---

libmvutil/src/uthread.c

Use the same setting as amd64 and arm32 for now, I have not quantified if this is the best value.
This removes the unknown arch warning on this architecture.

libmvutil: set pthread stack size on arm64

---

ssl-inspector/src/com/untangle/app/ssl_inspector/SslInspectorManager.java
uvm/hier/usr/share/untangle/bin/ut-certgen

The latest versions of iOS and macOS are enforcing strict requirements
on TLS certs. Ours seem to meet all of them except we use hard coded
start and end dates that result in a validity period of 28 years.
I updated the ut-certgen script so it will use current_time minus
one day as the start date which will prevent issues with minor clock
differences causing cert-not-yet-valid errors. I used a validity
period of 820 days to compensate for our one day start adjustment
plus a little extra room to be safe. I also updated the SSL Inspector
manager to look at the file modification time on MitM certs we cache
to improve performance, and force them to be recreated when they are
more than one year old.
@changelog

Fix to make generated certs compliant with new Apple requirements

---

buildtools/target.rb

C is the default locale on all the buildbot slaves instances, and also
in the more recent docker images used TravisCI; by also forcing ASCII
during the build, we expose potential failures during developer builds
where utf8-based locales are more common.

[buildtools Enforce reading JS files as ASCII

---

reports/hier/usr/share/untangle/bin/reports-create-csv.sh
reports/src/com/untangle/app/reports/ReportsApp.java

Leading -, ", + , @, and = in exported csv files need to be escaped with a single quote to
prevent formula injection

NGFW-12688 sanitize csv

---

uvm/hier/usr/lib/python2.7/dist-packages/uvm_login.py
uvm/hier/usr/share/untangle/web/auth/index.py

Currently callers of log_login pass the 'local' parameter to indicate
whether a login attempt is coming from the local box or not.
Unfortunately, most callers are not actually setting the local parameter
correctly.  Now, log_login checks if the request is local itself, and
sets the local flag accordingly.

NGFW-12669: uvm_login: Properly detect local login attempts

---

openvpn/src/com/untangle/app/openvpn/OpenVpnSettings.java

With 'keepalive 10 60' it takes 60 seconds for a client to determine
that a vpn connection has been lost before it does a soft restart to
try to reconnect.  On clients that might be sending all traffic through
the vpn (like an Untangle SDWAN router) that means clients behind the
router might not be able to send out any traffic for 60 seconds, which
seems like a long time.  A 10 second timeout with pings every 2 seconds
seems a bit more reasonable as far as making clients more responsive to
vpn connection drops, but not so drastic as to cause spurious restarts
on a spotty connection.
MFW-847

MFW-847: OpenVpnSettings: Set default keepalive settings to '2 10'

---

uvm/hier/usr/share/untangle/bin/ut-upgrade.py

It'll clean up any debs we have laying around in /var/cache/apt/archives
NGFW-12761

NGFW-12761: ut-upgrade: Run apt-get clean after upgrade

---

intrusion-prevention/hier/usr/share/untangle/lib/intrusion-prevention/appProperties.json

This is legacy behaviour from snort.  Now we do not require as much
memory with Suricata and we have rules to control how we use the
signature based on the amount of memory.
NGFW-12750

NGFW-12740: IPS: Remove minimumMemory requirement

---

libnetcap/src/netcap_tcp.c
libnetcap/src/netcap_tcp_cli.c
libnetcap/src/netcap_virtual_interface.c

IMPORTANT: This should not be merged until the updated kernel with the patch to the xt_mac module is available, otherwise it will completely break things as these changes depend on that kernel enhancement.
These changes for Citrix preserve the src and dst interface marks on packets, and encode both the src and dst interface marks in the src MAC address for packets re-injected on the utun device.

Citrix packet marks

---

debian/untangle-vm.preinst

In the past, ovas specified 2GB of ram.  Users who are still running
vms with 2GB of ram may run into memory pressure depending on what
apps they have installed.  This may even impair their ability to
upgrade.  To mitigate this, try to create and enable swap.
If we are upgrading to 15.0, and the box is a vm, and the box has
2GB of ram or less, and the box has 2GB or more of free disk space,
then create and enable a 2GB swap file before we start the upgrade
process.
NGFW-12733

NGFW-12733: untangle-vm.preinst: Add swap on vm with < 2GB ram

---

uvm/servlets/admin/app/overrides/form/field/VTypes.js

According to ietf rfc1034 [0] node labels have a maximum length
of 63 octets.  Prior to this change, urls with tlds greater than
5 were being truncated.
[0] https://tools.ietf.org/html/rfc1034
NGFW-12844

NGFW-12844: VTypes: ipOrUrl: Allow domains up to 63 characters

---

intrusion-prevention/hier/usr/lib/python3.5/dist-packages/tests/test_intrusion_prevention.py
uvm/js/common/reports/view/GraphReport.js

If 'nmap -sP' is run by an unprivileged user, it only uses TCP SYN
packets to 443 and 80 to ping the target.  These are not detected
by suricata as a network scan.  If run as root, 'nmap -sP' will
use ARP requests to ping the target.  These are also not detected
by suricata as a network scan.  If 'nmap -sP -PE --send-ip' is run
as root then nmap will actually send an icmp echo request that suricata
detects as a network scan.  However, we currently don't have a method
in our test framework of requesting that the remote nmap call be run
as root.  Instead we will use ping with 'ISSPNGRQ' specified in the
data section to trigger suricata sid: 2100465 "GPL SCAN ISS Pinger".
NGFW-12384

NGFW-12384: intrusion-prevention: Use ping with specified payload for icmp test

---

tunnel-vpn/src/com/untangle/app/tunnel_vpn/TunnelVpnMonitor.java
tunnel-vpn/src/com/untangle/app/tunnel_vpn/TunnelVpnTunnelStatus.java

Previously, we were storing the last traffic check time globally.
This works fine with a single tunnel, but breaks tunnel statistics
if there are multiple tunnel vpns.  In the case of multiple tunnels,
if it was time to update statistics, the first iteration through the
loop would set the lastTrafficCheck global when it generated a
statistic for the first tunnel.  On subsequent iterations through
the loop, for subsequent tunnels, the check of lastTrafficCheck
would always fail and we would therefore never generate a statistic
event for those tunnels.
Now we store the lastTrafficCheck value in the per tunnel status
so that we properly detect when it is time to generate a statistic
for each tunnel.
NGFW-12864

NGFW-12864: tunnel-vpn: Store last traffic check time per tunnel

---

http-casing/src/com/untangle/app/http/RequestLine.java
threat-prevention/hier/usr/share/untangle/lib/threat-prevention/reports/web-all-web-events.json
threat-prevention/src/com/untangle/app/threat-prevention/ThreatPreventionHttpsSniHandler.java
uvm/api/com/untangle/uvm/vnet/SessionAttachments.java
web-filter-base/src/com/untangle/app/web_filter/WebFilterHttpsSniHandler.java

This PR contains some temporary fixes prior to 15.0 until NGFW-12885 is implemented.
We were creating double the amount of events in the http_events table due to our current HTTPS SNI implementation between Web Filter and Threat Prevention. This was causing a doubling up of events for every HTTPS request that went through the Threat Prevention and Web Filter applications. Our temporary fix is to use the session globals to store the RequestLine, RequestLineToken, and HttpRequestEvent objects in the session globals for a given Session ID. This will allow the applications to function properly, while also cutting down on the amount of events generated.

Ngfw 12878 duplicate web filter events

---

threat-prevention/src/com/untangle/app/threat-prevention/ThreatPreventionDecisionEngine.java

We have seen a case where the host specified in the "Host" header
had the port appended.  bctid doesn't handle requests with the
port specified in the url.
Example:
This request would get its reputation reported correctly:
wget ws.trackmytime.com
But this one would not:
wget --header="Host: ws.trackmytime.com:80" ws.trackmytime.com
Since we know bctid can't handle the port, strip it from the host
if it exits, before we send the reputation request to bctid.
NGFW-12877

NGFW-12877: threat-prevention: Handle "Host" headers with appended port

---

uvm/api/com/untangle/uvm/app/AppBase.java
uvm/api/com/untangle/uvm/app/SessionTuple.java
uvm/impl/com/untangle/uvm/ConntrackMonitorImpl.java
uvm/impl/com/untangle/uvm/NetcapConntrackHook.java
uvm/impl/com/untangle/uvm/NetcapHook.java
uvm/impl/com/untangle/uvm/PipelineFoundryImpl.java
uvm/impl/com/untangle/uvm/SessionMonitorImpl.java
uvm/impl/com/untangle/uvm/SessionTableImpl.java

I don't know of any way to test this outside the actual environment where this issue was discovered, so my recommendation is to do a normal regression test to make sure this doesn't introduce new problems with normal traffic processing, and then create a release that can be provided to anyone who needs this functionality.
Here are the details:
I enhanced the uvm to include the source interface in the SessionTuple we use when caching sessions that are being processed. This should resolve an issue where we can't properly handle two identical sessions on different VLAN's.
Historically we have cached active sessions based on a 5-tuple:
proto+src_addr+src_port+dst_addr+dst_port
Before this change, creating an identical session on a second VLAN would not work, because the uvm would see the …

Vendor1 session tuple

---

openvpn/src/com/untangle/app/openvpn/OpenVpnAppImpl.java

When we remove a remote server configuration from an openvpn client,
make sure we actually stop the openvpn process when we are cleaning
up.
NGFW-13045

NGFW-13045: openvpn: Stop client process for removed remote servers

---

uvm/hier/usr/share/untangle/bin/ut-radius-logfile
uvm/impl/com/untangle/uvm/LocalDirectoryImpl.java
uvm/servlets/admin/config/local-directory/MainController.js
uvm/servlets/admin/config/local-directory/view/Radius.js

I think this is ready for testing. One critical thing... don't forget to add an access rule to allow RADIUS traffic (UDP port 1812) from the wireless access point to the Untangle. We'll likely do this automatically in a future release, but since for now this is expert-mode only, the rule creation is manual.
In my environment, I have my access point connected to the LAN, so I created an access rule to allow all UDP 1812 traffic from non-WAN's.
My UT = 192.168.20.1
My WAP = 192.168.20.222
My clients = 192.168.20.100 - 192.168.20.200
Configure your access point to do WPA/WPA2 Enterprise, and provide the IP address and shared secret configured on the untangle. That should be it. Once configured, clients should be able to connect to the WiFi by providing a username/password configured in the …

Ngfw 12914 local radius server

---

wireguard-vpn/hier/usr/share/untangle/lib/wireguard-vpn/reports/wireguardvpn-connect-events.json

Fixed a typo in the database table name of the connection events report.

Fix table name in wireguard connection events report

---

openvpn/src/com/untangle/app/openvpn/OpenVpnAppImpl.java

When cleaning up remote servers, if we find one that still exists,
but is not enabled, call systemctl stop to make sure its not
running, as it may have just been disabled

NGFW-13045: openvpn: Stop client process for disabled remote servers

---

ipsec-vpn/hier/usr/share/untangle/bin/ipsec-reload

Really only an issue during ATS runs where IPsec settings get updated
quickly many times in a row, triggering the systemd protection thing.
systemd[1]: xl2tpd.service: Start request repeated too quickly.
systemd[1]: xl2tpd.service: Failed with result 'start-limit-hit'.
Solved by calling reset-failed to prevent triggering the quick restart limit.

Fix issue with xl2tpd daemon restart

---

ipsec-vpn/js/view/IpsecTunnels.js
ipsec-vpn/src/com/untangle/app/ipsec_vpn/IpsecVpnApp.java
ipsec-vpn/src/com/untangle/app/ipsec_vpn/IpsecVpnDataTimer.java
ipsec-vpn/src/com/untangle/app/ipsec_vpn/IpsecVpnEvent.java
ipsec-vpn/src/com/untangle/app/ipsec_vpn/IpsecVpnPingTimer.java
ipsec-vpn/src/com/untangle/app/ipsec_vpn/IpsecVpnTunnel.java

This is ready for merge and testing. See the Jira ticket for low level implementation details.
The tunnel up/down detection and force restart logic has been reworked and is now completely driven by the ping target configured for the tunnel. If there is no ping target configured, we will not generate up/down events, and we will not attempt to detect or restart failed tunnels. As before, the configured ping target must only be reachable across the IPsec tunnel.
For testing, I would recommend bringing up an IPsec tunnel between two devices and configuring a valid ping target. Interrupting the tunnel (ie: unplug network cable) should cause a tunnel DISCONNECT event to be generated after at most 20 seconds. You will also so UNREACHABLE events for all ping failures. After around 60 seconds, you …

Ngfw 12983 ipsec tunnel reconnect

---

uvm/servlets/admin/config/administration/MainController.js
uvm/servlets/admin/config/administration/view/Certificates.js

Fix to hide the RADIUS checkbox column on the certificate selection
table if the expert mode flag is not set.

Hide RADIUS column on certificates table

---

bandwidth-control/hier/usr/lib/python3/dist-packages/tests/test_bandwidth_control.py

When we severely limit udp traffic, the maximum amount of data we are
going to receive is 10% of the determined wan download bandwidth.  So,
first we need to make sure the target udp bandwidth for the test is
always higher than that number.  Second, if the iperf test doesn't
receive ~60% or more of the requested udp bandwidth, the test run
will just fail and we won't get a test number at all.  So our target
number has to be low enough that limiting the bandwidth to 10% of
determined wan download bandwidth doesn't prevent more than 40% of
the test udp traffic from making it through.  So when calculating
the target udp bandwidth number, start with 10% of the determined
wan download bandwidth and then multiply by 1.6.
NGFW-13082

tests: bwc: Pick better udp iperf test numbers

---

uvm/hier/usr/bin/uvm

The systemd-tmpfiles-setup service is responsible for creating the
/dev/net/tun devnode on boot up.  But we have observed a number of
cases (usually after a kernel upgrade) where the /dev/net/tun node
was not created before we started the uvm.  Thats bad, because we
can't initialize netcap without it.  Since we know we are always
going to need /dev/net/tun (which is backed by the tun kernel
module) just go ahead and make sure the tun module is inserted
prior to starting the uvm.
NGFW-13144

uvm: Load tun module before starting uvm

---

ipsec-vpn/js/view/VpnConfig.js
ipsec-vpn/src/com/untangle/app/ipsec_vpn/IpsecVpnManager.java
ipsec-vpn/src/com/untangle/app/ipsec_vpn/IpsecVpnSettings.java

For ipsec tunnels we have a curated set of ike and esp ciphers.  Use
those same ciphers for l2tp/xauth/IKEv2.  This ensures we've got a
compatible cipher for android devices.  Also add the same manual
configuration settings for ike and esp that are available for ipsec
tunnels for customers who want to nail down a specific cipher.
NGFW-13163

ipsec-vpn: l2tp: Use same ciphers as ipsec tunnels

---

uvm/api/com/untangle/uvm/LocalDirectory.java
uvm/api/com/untangle/uvm/SystemSettings.java
uvm/hier/usr/share/untangle/bin/ut-radius-proxy
uvm/impl/com/untangle/uvm/LocalDirectoryImpl.java
uvm/impl/com/untangle/uvm/SystemManagerImpl.java
uvm/servlets/admin/config/local-directory/Main.js
uvm/servlets/admin/config/local-directory/MainController.js
uvm/servlets/admin/config/local-directory/view/Radius.js
uvm/servlets/admin/config/local-directory/view/RadiusLog.js
uvm/servlets/admin/config/local-directory/view/RadiusProxy.js
uvm/servlets/admin/config/local-directory/view/RadiusServer.js

This branch includes the NGFW user interface and uvm enhancements to support the RADIUS Phase 2 project. Like Phase 1 of this project, the expert-mode-flag must be enabled to activate and use these features, and everything is configured under Config / Local Directory.
We're calling this an engineering alpha release, so the supporting Debian packages are not yet integrated as part of our standard platform due to the additional size it will add to our distribution. Thus, to use these features, you must download and install the following development provided package:
wget http://auth-relay.untangle.com/netdev/ngfw-radius-proxy.tar.gz
Once you have a machine installed with a build that includes these changes, download the archive from the link above, extract into a convenient location, and …

Ngfw 13089 radius phase two

---

uvm/js/common/reports/view/Entry.js
uvm/js/common/reports/view/EventReport.js

In NGFW-12571 the 'Export Data (csv)' button was changed to export
the displayed report data, instead of the data returned by the
database query.  This commit changes the 'Export Data (csv)' button
to a menu button with options to export the queried data or just the
displayed data.
NGFW-12916

reports: Add back the ability to export full report database

---

wireguard-vpn/js/Main.js
wireguard-vpn/js/MainController.js
wireguard-vpn/js/view/Status.js

I changed the column header on the endpoint detected by the wireguard daemon to Detected Endpoint and made it hidden by default. I then updated the status display to get and use the configured endpoint address as the Remote Endpoint by default. This should clear up the confusion described in the ticket.

Fix how the endpoint is displayed in the status grid

---

intrusion-prevention/hier/etc/cron.daily/intrusion-prevention-get-updates

On older installs /bin is not symlinked to /usr/bin and so
the version lookup fails.  /usr/bin/suricata will work for new
and old installs.
NGFW-13187

intrusion-prevention-get-updates: Use /usr/bin/suricata

---

uvm/impl/com/untangle/uvm/LocalDirectoryImpl.java

We try to write /etc/samba/smb.conf but the directory won't exist if the RADIUS 2 stuff in advanced mode hasn't been enabled and the extra packages manually installed. I added a check to look for the /etc/samba directory before trying to write the config file so we won't pollute the log with an unnecessary exception.

Fix handling of samba configuration file

---

uvm/js/common/util/Util.js

I fixed the urlValidator to allow all legal TLD's from 2 to 63 characters in length.

Fix urlValidator to allow all valid TLD's

---

uvm/impl/com/untangle/uvm/NetworkManagerImpl.java

Whether they came from a user mucking with their settings
or a bug in our code, if there are duplicate interfaceIds,
bad stuff will happen.
NGFW-13209

NetworkManager: Check for duplicate interfaceIds

---

reports/js/MainController.js

The Reports UI was already getting the Google Drive connection status from the correct location after the move from Directory Connector to the core uvm. It seems the redirect target on the Configure Google Drive button just never got updated. I fixed and verified the button functionality, confirmed expected behavior both with and without Google Drive configured, and manually ran the reports google backup cron scripts to confirm that backups are properly generated and pushed to the configured location.

Fix reports link to Google Drive configuration

---

wireguard-vpn/src/com/untangle/app/wireguard_vpn/WireGuardVpnApp.java

Added null check for the passed status list and for each masked address in the list when building the network list to solve a null pointer exception I saw during app installation.

Check for null pointers when building network list

---

uvm/impl/com/untangle/uvm/CertificateManagerImpl.java
uvm/impl/com/untangle/uvm/LocalDirectoryImpl.java
uvm/servlets/admin/config/administration/view/Certificates.js
uvm/servlets/admin/config/local-directory/Main.js
uvm/servlets/admin/config/local-directory/MainController.js
uvm/servlets/admin/config/local-directory/view/RadiusProxy.js
uvm/servlets/admin/config/local-directory/view/RadiusServer.js

The main change was to remove expert mode protecting access to the RADIUS proxy feature. Fixed UI so the RADIUS server must be enabled before the proxy feature can be enabled. Fixed mschap configuration file so server_only and server+proxy modes both work.

Make RADIUS Proxy generally available

---

uvm/servlets/admin/config/local-directory/MainController.js

Previously, it was a bit confusing in that you could enter all of the details for the Active Directory Server, yet then clicking the Create AD Computer Account would fail. The issue is that the server configuration must be saved and applied before the account creation and authentication test will work properly. I added validation that displays an alert message when trying to use either function before the configuration changes have been saved.

Add change detection to account and test functions

---

wireguard-vpn/hier/usr/share/untangle/lib/wireguard-vpn/appProperties.json

The application needs to list the license app as a parent otherwise it can be instantiated before the license manager has fully initialized, causing the startup license check to fail.

Fix license check during startup

---

uvm/impl/com/untangle/uvm/HostTableImpl.java

Removed the automated update of usernames to the device table. This caused confusion as to the login status of a user and deviated from previous behavior.

NGFW-13468 Undo hostable to device table sync.

---

uvm/impl/com/untangle/uvm/SystemManagerImpl.java
uvm/servlets/admin/config/local-directory/MainController.js
uvm/servlets/admin/config/local-directory/view/RadiusProxy.js

The UI throws a bunch of exceptions and failure messages generated from exec'ing the create computer account command when called in the setSettings function. This happens when testing on a clean and never before configured system (ie: all settings wiped). Maybe a timing thing between the saving of the files, and restarting the external daemons? Not sure but I couldn't figure it out so I restored the UI button for manually creating the computer account and commented the auto create logic as a quick fix until we can do more analysis.

Disable RADIUS Proxy auto account creation

---

uvm/servlets/admin/config/local-directory/view/RadiusProxy.js

Remove the need to have "important" text in the wiki that you need to have the AD Workgroup UpperCase.
https://wiki.untangle.com/index.php/RADIUS_Proxy

Force Uppercase on Radius Proxy AD Workgroup text field

---

docs/EventsDescriptionExtensionImpl.java
docs/EventsDocumentationExtensionImpl.java
docs/reports-generate-docs-db-schema.py
reports/hier/usr/lib/python2.7/dist-packages/reports/untangle_vm.py
reports/src/com/untangle/app/reports/EventWriterImpl.java
reports/src/com/untangle/app/reports/ReportsApp.java
uvm/api/com/untangle/uvm/CriticalAlertEvent.java
uvm/api/com/untangle/uvm/app/Reporting.java
uvm/hier/usr/share/untangle/lib/untangle-vm/events/classFields.json
uvm/impl/com/untangle/uvm/EventManagerImpl.java
uvm/impl/com/untangle/uvm/NotificationManagerImpl.java
uvm/js/common/util/_Map.js

Added logic to stop capturing reporting data when free disk space falls below 5GB to preserve system function and stability. When the condition is triggered, an alert will be displayed in the user interface and will be generated and sent via the standard alert email mechanism. When free disk space is no longer below the threshold, capture of reporting data will resume, the user interface alert will be cleared, and a "service restored" alert will be generated.

Add logic to stop reporting when disk nearly full

---

wireguard-vpn/hier/usr/share/untangle/lib/wireguard-vpn/reports/wireguardvpn-events.json
wireguard-vpn/hier/usr/share/untangle/lib/wireguard-vpn/reports/wireguardvpn-monitor-events.json

Since we don't have real connection events for wireguard, call
then monitor events instead
NGFW-13289

wireguard: Tweak report names/descriptions

---

uvm/impl/com/untangle/uvm/NetworkManagerImpl.java

Older systems may not have a readOnly boolean on access rules which can cause a null pointer exception when trying to add the new RADIUS rules. Fixed by not using the readOnly flag.

Fix RADIUS rule upgrade on older installations

---

ipsec-vpn/src/com/untangle/app/ipsec_vpn/IpsecVpnApp.java
openvpn/src/com/untangle/app/openvpn/OpenVpnAppImpl.java
uvm/api/com/untangle/uvm/NetspaceManager.java
uvm/impl/com/untangle/uvm/NetspaceManagerImpl.java
wireguard-vpn/src/com/untangle/app/wireguard_vpn/WireGuardVpnApp.java

Our previous implementation could fail and return a problematic default in some cases, particularly if the entire 10.0.0.0/8 network was already consumed such as when assigned to the LAN device. I replaced the random generation approach we used for IPv4 with a more structured mechanism that works through all of the RFC1918 reserved space in sequence. I also simplified things so we'll always use /24's as the auto-generated defaults since there isn't any reason or facility provided to automatically request a network of arbitrary size. This new method also handles a very rare edge case where an app might request multiple blocks before the settings are saved, which is when assigned networks are registered. Since we now try them in order, there is no chance we'll randomly generate the same …

Rework the getAvailableAddressSpace function

---

application-control/hier/usr/share/untangle/lib/application-control/appProperties.json
bandwidth-control/hier/usr/share/untangle/lib/bandwidth-control/appProperties.json
branding-manager/hier/usr/share/untangle/lib/branding-manager/appProperties.json
captive-portal/hier/usr/share/untangle/lib/captive-portal/appProperties.json
configuration-backup/hier/usr/share/untangle/lib/configuration-backup/appProperties.json
directory-connector/hier/usr/share/untangle/lib/directory-connector/appProperties.json
firewall/hier/usr/share/untangle/lib/firewall/appProperties.json
ipsec-vpn/hier/usr/share/untangle/lib/ipsec-vpn/appProperties.json
live-support/hier/usr/share/untangle/lib/live-support/appProperties.json
openvpn/hier/usr/share/untangle/lib/openvpn/appProperties.json
policy-manager/hier/usr/share/untangle/lib/policy-manager/appProperties.json
reports/hier/usr/share/untangle/lib/reports/appProperties.json
ssl-inspector/hier/usr/share/untangle/lib/ssl-inspector/appProperties.json
threat-prevention/hier/usr/share/untangle/lib/threat-prevention/appProperties.json
tunnel-vpn/hier/usr/share/untangle/lib/tunnel-vpn/appProperties.json
uvm/api/com/untangle/uvm/app/AppProperties.java
uvm/impl/com/untangle/uvm/AppManagerImpl.java
virus-blocker/hier/usr/share/untangle/lib/virus-blocker/appProperties.json
web-filter/hier/usr/share/untangle/lib/web-filter/appProperties.json
wireguard-vpn/hier/usr/share/untangle/lib/wireguard-vpn/appProperties.json

I added a new autoInstall flag to the AppProperties class. When set to true in the corresponding appProperties.json file, that app will automatically be installed when the uvm launches for the first time and initializes the default app manager settings. The new logic also honors the autoStart flag so apps can be set to auto install in either enabled or disabled mode. I then added autoStart:true to the 18 recommended apps we suggest the user install by default. Note that this logic is NOT triggered when isDevel() returns true to maintain the speed and overall consistency when working in the development environment.

Add logic to install recommended apps by default

---

ipsec-vpn/hier/usr/lib/python2.7/dist-packages/reports/ipsec_vpn.py
openvpn/hier/usr/lib/python2.7/dist-packages/reports/openvpn.py
tunnel-vpn/hier/usr/lib/python2.7/dist-packages/reports/tunnel_vpn.py
wireguard-vpn/hier/usr/lib/python2.7/dist-packages/reports/wireguard_vpn.py

In several apps we never added a call to clean_table in the reports python script which allowed the tables to grow perpetually with old data never being pruned.

Add missing clean_table call for several apps

---

uvm/api/com/untangle/uvm/UvmContext.java
uvm/impl/com/untangle/uvm/AppManagerImpl.java
uvm/impl/com/untangle/uvm/UvmContextImpl.java
uvm/servlets/admin/app/view/apps/AppsController.js

The recommended applications are now installed automatically, so we no longer need to prompt the user. In addition to removing the prompt window, I also fixed the auto install logic so the apps will now be installed after the uvm is fully initialized. This eliminates the uvm startup delay and allows the apps to get the proper trial license automatically. Added a new isAts() function that detects when running on an ATS system, and the auto install is now skipped in both DEV and ATS environments.

Remove window prompting to install default apps

---

license/src/com/untangle/app/license/LicenseManagerImpl.java

The license manager assumed the presence of seats in a license would always be a valid integer. This causes an exception if we find "seats": null in a license file. Added isNull check when attempting to parse the value.

Fix null handling in license manager

---

license/src/com/untangle/app/license/LicenseManagerImpl.java
live-support/js/view/Status.js

The live support app was indicating live support was available even with an expired license. Solved by hiding the Is Entitled message and Get Support button when the license is not valid. I also added logic to the license manager to look for NGFW_LICENSE_TEST in the environment to simplify testing the license stuff on dev systems.

Fix information displayed in the live support app

---

wan-failover/hier/usr/share/untangle/bin/wan-failover-test.sh

Improved output parsing so we don't pass something like 1.2.3.4/24 to the ping command and to look for the IP address immediately following the src tag instead of always expecting it to be in the 5th column of output.

Fix output parsing in failover tests

---

live-support/js/Main.js
live-support/js/MainController.js
live-support/js/view/Status.js
uvm/impl/com/untangle/uvm/UvmContextImpl.java

If the live support license is valid, we operate as we always have. A message indicates live support is entitled and the Get Support button will allow submitting a request. If the license is not valid, we display a message indicating live support is NOT entitled and a Learn More button will open the Live-Support app page on the Untangle website.

Rework live support message and buttons

---

ipsec-vpn/hier/usr/share/untangle/lib/ipsec-vpn/appProperties.json

Now that we autoInstall ipsec we need to make it NOT autoStart as command center has logic to handle things differently depending onwhich apps are installed and active. Added autoStart = false to appProperties.json so it will be included during autoInstall but will be turned off by default.

Turn off autoStart for ipsec

---

uvm/api/com/untangle/uvm/ConfigManager.java
uvm/api/com/untangle/uvm/InterfaceMetrics.java
uvm/hier/usr/share/untangle/bin/ut-factory-defaults
uvm/impl/com/untangle/uvm/ConfigManagerImpl.java

Since this branch still needs to be reviewed and merged, I added the fix for the doFactoryReset API call in this branch.
The existing ut-factory-defaults script stops and starts the uvm which prevented our API response for the reset command from being sent. It also doesn't make much sense to restart the uvm after restoring factory defaults since we're just going to reboot anyhow. I added a force-reboot flag to the ut-factory-defaults script that will reboot instead of restart the uvm when set, and we now use that script/flag to handle the reboot. Cleaner and more efficient that my original implementation.

Ngfw 13696 netgear port status api call

---

uvm/impl/com/untangle/uvm/ConfigManagerImpl.java

We need nohup when calling the ut-factory-defaults script

Fix doFactoryReset API call

---

uvm/api/com/untangle/uvm/ConfigManager.java
uvm/hier/usr/share/untangle/bin/ut-diagnostic-dump
uvm/impl/com/untangle/uvm/ConfigManagerImpl.java

Added the API function to create an archive of diagnostic info. The file is created by the new ut-diagnostic-dump script and will capture everything in /var/log, /etc, and the settings and conf directories under /usr/share/untangle. I also removed the API functions for traffic metrics and notifications since this data will be pulled using the doDatabaseQuery call. Cleaned up and enhanced the javadoc comments in a few places.

Add createDiagnosticDump API call to ConfigManager

---

reports/src/com/untangle/app/reports/EventWriterImpl.java
uvm/api/com/untangle/uvm/UvmContext.java
uvm/hier/usr/share/untangle/bin/ut-tempfs-setup
uvm/impl/com/untangle/uvm/UvmContextImpl.java

Added a flag and script that can move things to tempfs during startup to reduce wear on storage media with limited write cycles. Initial implementation moves only the database (postgres or sqlite) since I believe that is where the vast majority of disk thrashing originates. I didn't move /var/log since we plan to reduce noise there by changing our levels from INFO to ERROR and preserving what we do have across reboots may be of great benefit during diagnostic analysis.

Add support for using tempfs for eMMC preservation

---

uvm/api/com/untangle/uvm/InterfaceMetrics.java
uvm/impl/com/untangle/uvm/ConfigManagerImpl.java

Added the network config details (addr, netmask, etc.) to the InterfaceMetrics objects returned from the getNetworkPortStats call. Added a call to Uvm getApplianceModel so we return the correct model in the getSystemInfo call.

Add interface details and appliance model to API results

---

uvm/api/com/untangle/uvm/ConfigManager.java
uvm/impl/com/untangle/uvm/ConfigManagerImpl.java

Added a logger call to each public API function so we can track changes made using the new API functions. Fixed a minor issue in thegetNetworkPortStats function where it was calling getDeviceStatus multiple times which translated into multiple exec calls and added latency to the call.

Add logging to ConfigManager API calls

---

reports/src/com/untangle/app/reports/ReportsApp.java
uvm/hier/usr/share/untangle/bin/oem-settings-override.py

Added logic to apply OEM overrides to the default settings in the reports application. The reports settings are a bit more complicated than the others already completed, and this revealed some edge cases that the Python script wasn't handling properly. I added additional type checking in the recursive processing so we only recurse into child lists and dictionaries to resolve the issue. While tracking this down I discovered it was helpful to include the exception message in the error output when handling unexpected conditions. I also added sort_keys=True to the json.dump calls for the debug and final output files which helps when using diff to compare the original and modified json while testing.

Add OEM override processing to reports default settings

---

uvm/api/com/untangle/uvm/UvmContext.java
uvm/hier/usr/share/untangle/bin/ut-factory-defaults
uvm/hier/usr/share/untangle/bin/ut-tempfs-backup
uvm/hier/usr/share/untangle/bin/ut-tempfs-setup
uvm/impl/com/untangle/uvm/UvmContextImpl.java

When the tempfs-mode-flag is enabled, and the postgresql database is running from tempfs, we use an hourly Pulse to create a copy of the database on the physical disk using the pg_dump command. I then modified the ut-tempfs-setup script to restore the database from the backup file if it exists. I also added cleanup of the backup file to the ut-factory-defaults script.

Add persistence for the tempfs database

---

uvm/hier/usr/share/untangle/conf/apache2/conf.d/support.conf
uvm/impl/com/untangle/uvm/TomcatManagerImpl.java
uvm/package.rb
uvm/servlets/support/root/WEB-INF/web.xml
uvm/servlets/support/root/index.jsp
uvm/servlets/support/src/com/untangle/uvm/AdvancedSupportHandler.java

Our partner wants support for managing a simple daemon that provides remote access for their engineering support team via their existing infrastructure. To make this work, I have added a new servlet that is available at https://server_ip_address/support using the same authentication mechanism as our own admin UI. When GET and POST requests are received, the parameters are extracted and stored in a simple JSON object that is serialized using base64 and then passed to an external Python script along with the request method. The script processes the request and generates the HTML page that is returned to the client. This mechanism is a generic enhancement to our core platform. All of the vendor specific branding and functionality is handled in the new oem-support-handler script that will be …

Add support for Secure Diagnostic Mode control interface

---

license/hier/usr/share/untangle/lib/license/appProperties.json
license/src/com/untangle/app/license/LicenseManagerImpl.java
router/hier/usr/share/untangle/lib/router/appProperties.json
uvm/api/com/untangle/uvm/app/AppManager.java
uvm/impl/com/untangle/uvm/AppManagerImpl.java

Added logic to increase the retry frequency during startup when the license server is not accessible. When the initial license download is completed, the pulse is reset to use the standard interval.

Increase pulse interval when no internet during startup and deferred autoinstall logic

---

openvpn/hier/usr/share/untangle/bin/openvpn-auth-user-pass

We always want to use the mfa authentication method for VPN users. If a use in the local directory do not have MFA enabled, we default back to just checking username and password.

Always check for MFA on VPN connections

---

uvm/impl/com/untangle/uvm/ConfigManagerImpl.java

Added a check to make sure the /sys/devices/virtual/thermal directory exists before doing the file search to solve a null pointer exception during startup if the directory is missing.

Add exists check for thermal directory

---

.travis.yml

Even though the bullseye builds succeed on feature branches, they
systematically fail on the corresponding PR for a reason yet to be
determined.

travis: do not build PRs for bullseye

---

buildtools/uri-analyzer.py
uvm/api/com/untangle/uvm/UvmContext.java
uvm/hier/usr/lib/python3/dist-packages/tests/test_uvm.py
uvm/impl/com/untangle/uvm/UvmContextImpl.java
uvm/servlets/admin/app/view/main/MainController.js

As part of the Untangle rebranding to Arista we need to update the feedback link in NGFW so that it points to edge.arista.com/feedback. Same has been changed in this PR.
Refer below screenshots regarding the change, tested locally.
On clicking Suggest Idea button in nav bar user will be redirected to edge.arista.com/feedback and eventually to feedback page

ngfw-14476 updated feedback url

---

virus-blocker-lite/js/view/Advanced.js
virus-blocker/js/view/Advanced.js

- Using RegEx to allow alphanumeric and ^ ~ ! @ # $ - _ ? special characters only at the beginning of the file type extension for Virus Blocker and Virus Blocker Lite apps.
- Shows message for invalid character,
Ref: http://libs.gisi.ru/ext-6.2.0-docs/extjs/6.2.0/classic/Ext.form.field.Text.html#cfg-regex

NGFW-14380 Allowing specific characters for file type in virus blocker apps

---

ipsec-vpn/js/view/IpsecLog.js
ipsec-vpn/js/view/IpsecPolicy.js
ipsec-vpn/js/view/IpsecState.js
ipsec-vpn/js/view/L2tpLog.js
tunnel-vpn/js/view/Log.js

**Issue:** Log form fields in IPsec Vpn and Tunnel VPN are editable which should be read only.
**Fixed:** Added UI level restriction to make these fields readonly.
**Dev Tests:** 
1. Checked  all log form ipsec state, ipsec policy, ipsec log and L2TP log, after the fix these are not editable.
2. Also checked the log form of tunnel log, this is not editable.
**Before:**
**After:**

NGFW-14379: Revoking the update for log fields

---

virus-blocker-lite/js/view/Advanced.js
virus-blocker/js/view/Advanced.js

- Restricting first character to be alphanumeric or any one of those special characters ? ^ _ ~ ! @ # $ and -
- Earlier it was accepting a value that starts with restricted character followed by some string (for ex., `%test`)

NGFW-14380 Updated file type regex for virus blocker apps

---

uvm/servlets/admin/config/network/MainController.js

Resolved the bug [NGFW-14288](https://awakesecurity.atlassian.net/browse/NGFW-14288)
Added code to update network settings object while saving settings in case static dhcp entries are modified, deleted or added.
Below are the screenshots for local testing.
Added two duplicate DHCP entries (Config --> Network --> DHCP Server). On clicking save we get error prompt.
After deleting one of the duplicate entry user is able to save the settings.
[NGFW-14288]: https://awakesecurity.atlassian.net/browse/NGFW-14288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ngfw-14288 update static DHCP data on save settings

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_network.py

Problem: iptables rules for snort still exist, and these should be removed and the ips postinst updated to not have those. We use suricata now.
Changes:
The fix is addressed in PR https://github.com/untangle/sync-settings/pull/703
After changes are merged and built, follow the steps mentioned in above pr.
This PR adds a test case which will create a 740-snort ext file and runs sync settings which removes the snort file

ngfw-13495: remove snort files

---

uvm/api/com/untangle/uvm/MailSettings.java
uvm/hier/usr/lib/python3/dist-packages/tests/test_email.py
uvm/impl/com/untangle/uvm/MailSenderImpl.java
uvm/servlets/admin/config/email/view/OutgoingServer.js

@cblaise-untangle 
During investigation as per JIRA ticket
1. Mail relay through cloud hosted service is removed
a. UI changes required: option removal from UI can be done in this file
uvm/servlets/admin/config/email/view/OutgoingServer.js
b. Backend changes
/uvm/api/com/untangle/uvm/MailSettings.java:  this will require RELAY option to be changed to Direct
/uvm/impl/com/untangle/uvm/MailSenderImpl.java  : 
email settings are saved in backed from UI using setSettings method in a local mail.js file at    /usr/share/untangle/settings/untangle- vm/mail.js. 
there are some if conditions related to RELAY if (settings.getSendMethod() == MailSettings.SendMethod.RELAY) which needs to be removed along with other references
2. On upgrades, if the user has this option selected it will switch to send …

ngfw-14271: remove cloudhosted relay option

---

firewall/src/com/untangle/app/firewall/FirewallEvent.java

Acceptance criteria:
The event Summary field should begin with "Firewall passed ..." instead of "Firewall password"
Made required changes in FirewallEvent.java , 
During testing added firewall rule in firewall app to  unblock 13.59.216.148 80 port and it is being captured in firewall reports,
Firewall rule, note the rule id
Add alert rule in config/alerts as following
select class as  FirewallEvent and  for conditon select rule id, and value as obtained in above and save
From test machine run following command
telnet 13.59.216.148 80 
Firewall rule executed
Event summary changed to passed instead of password

ngfw-13568: change password to passed

---

uvm/servlets/admin/app/overrides/form/field/VTypes.js

Currently in NGFW router rules like NAT, Bypass and filter rules IP address port numbers 0 and 65536 are accepted.
Modified validation function to limit the range to **1-65536**.
While doing analysis found validation passing for `<1` and `>65535` inputs though these are invalid inputs. hence changed portMatcher function to accept only valid inputs like `<=1`(only one value is valid i.e. 1) and '>=65535' (only one value is valid i.e. 65535).
Local Testing Screenshots

ngfw-13410 portMatcher VType modified for ip port validation bug

---

uvm/servlets/setup/app/view/step/Internet.js

If NGFW is offline, during the Internet connection step, there was no clear instructions that the user has to press test connectivity to proceed to the next step.
Added the instruction _No Internet Connection..! Click on 'Test Connectivity' to verify._  if there is no internet connection.
Configure Internet Connection page at installation start up.
Configure Internet Connection page in local set up wizard

ngfw-13889 added instruction to test connectivity on Internet page

---

license/src/com/untangle/app/license/LicenseManagerImpl.java

Testing Steps
Do a fresh install of NGFW, add ngfw in ETM, trial license should be applied
change log level for license app from WARN to INFO
nano /usr/share/untangle/conf/log4j.xml
<category name="com.untangle.uvm.license">
<priority value="INFO"/>
</category>
restart uvm
/etc/init.d/untangle-vm restart
install spam-blocker app
verify that there will be entries for &node=spam-blocker &node=spamblocker (2 entries with &node for spam-blocker and spamblocker)
in /var/log/uvm/app-1.log
grep -R "node=spam" /var/log/uvm/app-1.log 
Apply the patch
install wan-failover app
verify that there will be no  entries for &node=wan-failover &node=faild (0 entries with &node for wan-failover and faild) in
/var/log/uvm/app-1.log
grep -R "node=wan" /var/log/uvm/app-1.log 
After test revert back original …

ngfw-13739: NGFW sending incorrect startTrial request

---

uvm/servlets/setup/app/Application.js
uvm/servlets/setup/app/view/step/Internet.js

1. Added V-Type `ip4Address` in `Application.js` to validate Static IP fields on Configure Internet Connection Page.
2. Changed the default validation for STATIC container from  `ipAddress` to `ip4Address` and overwritten validation for Netmask Field to `ipAddress`.
Local Testing Screenshots

ngfw-13407 static ip validation on configure internet page

---

tunnel-vpn/js/view/Tunnels.js

While adding tunnel in Tunnel VPN app using provider with username and password fields, was able to add tunnel without username and password.
Made Username and password fields mandatory.
Local testing Screenshots

ngfw-14177 not allowing blank values in tunnel vpn provider creds

---

license/src/com/untangle/app/license/LicenseManagerImpl.java
uvm/hier/usr/lib/python3/dist-packages/tests/test_uvm.py

Acceptance Criteria: 
Keep last 5 days license files in (/usr/share/untangle/conf/licenses) and prune rest of them
This will prune number of license files to 5
Added test case to support this change.
PFA screenshot
Initally no of files are > 5, after upgrade no of files is <=5 
Testing steps:
1. Before upgrade
cd /usr/share/untangle/conf/licenses
ls -ltr    (number of license files > 5)
3. After Upgrade the ngfw with these changes 
ls -ltr    (number of license files <= 5)

ngfw-13806: remove old license settings files

---

buildtools/uri-analyzer.py
uvm/api/com/untangle/uvm/UriManagerSettings.java
uvm/impl/com/untangle/uvm/UriManagerImpl.java
uvm/impl/com/untangle/uvm/UvmContextImpl.java

1. Help linked modified to use HTTPS.
2. Using `UriManager` to store link and get the link.
3. Updated `untangle-region-eu` Package,  Added help base url `https://wiki.edge.arista.com/get.php` in uris_override.js file 
[PR ngfw_pkgs](https://github.com/untangle/ngfw_pkgs/pull/92)
Local Testing:
- Built the updated package `untangle-region-eu` using command `PACKAGE=untangle-region-eu FORCE=1 VERBOSE=1 UPLOAD=local docker compose -f docker-compose.build.yml run build`.
- Installed the package on local NGFW
- Added logs to track whether `UriTranslations` is getting correctly updated.
- Built the changes in local and tested help button on UI
- Verified url in logs using `/var/log/uvm/uvm.log` file.
- Removed logs added for testing

ngfw-13910 updating help link and using uri manager to access it

---

uvm/js/common/ungrid/RecordDetailsController.js

**Issue:** 
This issue comprises two separate issues:
This issue is also persisted in config->Advanced->networkCards.
1. The value field for each datum is blank as shown in video.
2. Each row can be selected multiple times because onBeforeRender is calling each time while selecting the field.
https://github.com/untangle/ngfw_src/blob/c9cd422718f7b3075292fefc0a46aececd3050e9/uvm/js/common/ungrid/RecordDetailsController.js#L45
**Note:**
As per discussion with @cblaise-untangle the filed should not be selectable once rendered in Grid. So done the changes and testing as per suggestion.
**Fix:**
- Put a condition to render mastergrid only once.
**Test:**
Testing of this fix includes multiple forms:
1.  Config-> Interface -> status
2.  Advanced -> networkCards ->status
3. Devices
4. Hosts
5. …

NGFW-14069 : UI discrepancy in NGFW Interface Status

---

.vscode/vsbuild.sh
uvm/hier/usr/share/untangle/lang/lang.cfg

**Issue** : Extra test entry present in the language file.
**Fix** : 
1) Removed extra entry, also added rsync for that file.
2) Restart the UVM : /etc/init.d/untangle-vm restart
before :
after :

Test language removed and rsync added

---

uvm/impl/com/untangle/uvm/EventManagerImpl.java

Issue: NGFW events with SClientAddr != <specified ip > should not be sent to syslog reciever 
RCA:
In EventManagerImpl class, runSyslogRules method for LogEvent object is converted to  two JSONObjects,
jsonObject and jsonSendObject, the jsonSendObject is further sanitized using cleanupJsonObject method,
During syslog rule validation  jsonObject is used presently, so the value of SClientAddr starts with "/" i.e. "/192.168.1.100" 
during matching/validation it is compared with syslog rule which has  value "192.168.1.100" and condition as "!=" for SClientAddr,
which never matches and logs are sent to syslog reciever to irrespective of the rule.
PFA debugging screenshot without fix, refer "valueStr" and "fieldValue" of compared jsonobject and rule object respectively
match is shown as false …

ngfw-13690: syslog Syslog SClientAddr != conditional filter doesn't work

---

uvm/servlets/admin/app/view/main/Offline.js

Testing Steps
Set up NGFW without Internet access and refer to the final step after saying yes to connecting to Command Center.
Expected:
- The next steps are registration and installing apps from the APPS menu.
- Your server was unable to connect to the internet.
Actual:
- The next step are registration and installing apps from the App Store.
- Your server was unable to contact the App Store.
Before making changes, PFA screenshot:
After making changes , PFA  screenshot
@cblaise-untangle "installing apps from the APPS menu."  APPS menu is fine or something else should be used here.

ngfw-13720: Failed connection page after setup wizard refers to App Store

---

wireguard-vpn/js/view/Settings.js

Validation for KeepAlive field,
Accepts: 50, 120, 50000
Rejects: -1, --1, 0, 00, 0120, 10-, 500000 (digits more than 5)

NGFW-13561 Regex validation for Keep Alive setting in Wireguard VPN

---

uvm/servlets/admin/config/network/Interface.js

**ISSUE:** Interface name should not be same 
**FIX:**  Adding validation to check uniqueness of interface name while creating VLAN interface
**TEST:**  
Tested below case:
1- While adding new VLAN Interface
2- While updating existing VLAN Interface
a. Trying to update interface name with already existing name.
b.Trying to update other filed in edit form

NGFW-13434: Interface names are able to be the same as another interface

---

uvm/servlets/setup/app/view/Main.js
uvm/servlets/setup/app/view/Util.js

If attempting to start the offline setup wizard on a device that already has an non admin password set, you will get an "Authentication failed" popup and will not be able to progress.
Steps to Reproduce: 
1. Add an NGFW to an ETMD account and configure an admin password for it.
2. Disconnect the WAN from the NGFW.
3. Navigate to Config > System > Support and press the "Launch Setup Wizard" option
4. attempt to complete the offline wizard.
Step 3 not present in UI
RCA:
if internet is not present on device and device has a non-default admin password,  then  Offline setup wizard cannot be started and error is shown as invalid password because, in that scenario in Main.js
following code is called, which has default admin password hardcoded
```
Util.authenticate("passwd", function () { …
```

ngfw-14283: Offline setup with non admin password

---

license/src/com/untangle/app/license/LicenseManagerImpl.java

Although we do check for the connectivity before downloading the licenses, there may be a possibility that the connectivity is lost after our test. To allow reading licenses from the local file we must catch IllegalArgumentException that is being thrown from `loadUrl()` method.

NGFW-14005 Handling IllegalArgumentException while downloading licenses

---

tunnel-vpn/js/view/Tunnels.js

Removing copy action from Apps --> Tunnel VPN --> Tunnels as every record should have separate configuration file and it should not be copied.

ngfw-13247 removing copy action for Tunnel VPN - Tunnels

---

uvm/servlets/admin/config/network/Interface.js
uvm/servlets/admin/config/network/MainController.js

Added a validation function to _IPv4 Aliases_ tab In _Add/Edit VLAN Interface_ window.
1. default alias address is set to  blank string `''`. If user does not change it he will be shown validation error `This field is required`. If he still continues with default address the record will be dropped on clicking `Done` button.
2. Validator checks for duplicate alias address in same Interface. If found it returns error string `Duplicate IPv4 alias address` and won't allow user to add duplicate address.
3. Validator checks for duplicate alias address in other all interfaces. If found it returns error string `Interface with this alias IPv4 address already exists` and won't allow user to add duplicate address.

ngfw-13472 added validator for staticAddress field in Alias IPv4

---

openvpn/js/MainController.js

Updated **Get Client Configuration** verbiage in OpenVPN App from `Click here to download this client\'s configuration as a single ovpn file with all certificates included inline (For use with OpenVPN Connect App).`  to `Click here to download this client\'s configuration as a single ovpn file with all certificates included inline (For use with OpenVPN Community Edition).`
Path - Apps --> OpenVPN --> Server --> Remote Clients --> Get Client Configuration

ngfw-14514 OpenVPN Download client configuration verbiage updated

---

uvm/servlets/admin/config/network/Interface.js

- Set minimum value to 120 for DHCP Lease Duration

NGFW-13441 Set minimum value of 120 for DHCP Lease Duration

---

openvpn/js/view/Server.js
openvpn/src/com/untangle/app/openvpn/OpenVpnAppImpl.java

Fixed backend parameter to register the remote client network. We are now able to save remote client network addresses.
Added emptyText to the field

NGFW-13500 Fixed openssl remote clients backend exception

---

uvm/servlets/admin/config/network/Interface.js

**ISSUE:** Vlan Tag can be created with same name.
**FIX:** Added validator to allow unique VlanTag under same parent device.
**TESTING STEPS:**  
1. Go to : Config>Network>Interface
2. Validate that no two devices which have the same parent device can have the same VLAN tag.
3.  Validate if the parent is different, then devices can have the same tag attached.

NGFW-13435: Added validator To Have Unique VlanTag Under SameParent Device

---

uvm/servlets/admin/app/overrides/form/field/VTypes.js

**ISSUE:**  Fields which supposed to have CIDR notation, can be saved without CIDR notation.
**FIX:** Fixed the regex to make CIDR notation mandate.
**TEST:** This change will apply to multiple apps.
Below fields needs to be tested:
1. Apps>OpenVPN>Server>Exported Networks>Add>Network Field
2. Apps>IpsecVPN>GreNetworks>GRE Address Pool Field
3. Apps>IpsecVPN>IpsecTunnels>Local Network Field
4. Apps>IpsecVPN>IpsecTunnels>Remote Network Field
5. Apps>IpsecVPN> VpnConfig>virtual Address Pool Field
6. Apps>WireGuardVPN>Setting>Network Address Field
7. Apps>WireGuardVPN>Tunnels>Remote Networks Field

NGFW-13849: Fixed the regex to validate CIDR entry

---

uvm/js/common/util/Util.js
uvm/servlets/admin/config/network/Interface.js

Added a validator for IPv4 Address Field for ADDRESSED and STATIC Interface configurations such that conflicting IPv4 addresses can't be saved.
Local Testing Screenshots
If user tries to enter the address conflicting with any of the ADDRESSED and STATIC configured IPv4 Interface, error message will be shown - `Conflicting Netmask for Interfaces {interface1} and {interface2}`

ngfw-13541 validation added for Lan ipv4 netmask

---

wireguard-vpn/js/view/Settings.js

Added validator for Network Space on Page - WireGuard VPN --> Settings.
If user enters conflicting ip address with network address pool then below error will be shown and user won't be able to save settings.

ngfw-13479 validator added for wiregurad vpn - Network Space

---

uvm/js/common/util/Renderer.js
uvm/js/common/util/_Map.js

Acceptance criteria: 
Add New WebFilter Categories, for report library
85, "Self Harm
86, "DNS Over HTTPS"
87, "Low-THC Cannabis Products"
88, "Generative AI"
Testing steps:
1. Block and flag  access to DNS Over HTTPS, Generative AI,  Alcohol and Tobacco from App web filter categories tab
2. Search for this site which is  related to DNS Over Https in browser (https://cloudflare-dns.com/dns-query?name=example.com&type=A) from client behind NGFW
Ideally Webfilter should block this site, however NGFW's bright cloud definitions classify it under web category Proxy Avoidance and Anonymizers, which might be due to bright cloud definitions not being updated, unless they are not updated it will not be classified.
Verified this site (https://cloudflare-dns.com/dns-query?name=example.com&type=A) on …

ngfw-14530: New WebFilter Categories need to be in report libary

---

uvm/js/common/util/Util.js
uvm/servlets/admin/app/overrides/form/field/VTypes.js
uvm/servlets/admin/config/network/Interface.js

Not allowing 0.0.0.0/0 for interface IPv4 address fields at
- Interfaces --> Add/Edit Interface --> IPv4 Configuration --> Static
- Interfaces --> Add/Edit Interface --> IPv4 Configuration --> Auto (DHCP)
- Interfaces --> Add/Edit Interface --> DHCP Configuration

ngfw-14198 Not allowing 0.0.0.0/0 for interface ipv4 addresses

---

wireguard-vpn/js/view/Tunnels.js

**ISSUE:** Able to add multiple wireguard VPN client tunnels with same data.
**FIX:**  Added validation to check uniqueness of Description, Peer IP Address and Public key fields.
**TEST:** 
1. Go to App>WireGaurdVPN>Tunnel
2. Check validation for  Description, Peer IP Address and Public key fields by adding same value present in existing record.

NGFW-13482: Added validation for Wireguard VPN Tunnel form

---

uvm/js/common/ungrid/GridController.js
uvm/js/common/util/Util.js
wireguard-vpn/js/MainController.js
wireguard-vpn/js/view/Tunnels.js

Changes:
1. for `recordAction` `copy` - Modified `copyModify` functionality to support functions .
2. Added copyModify property to Wireguard VPN --> Tunnels grid.
When user will click on copy action on `Tunnels` page then record will be copied and new unused ip address will be assigned to `Remote Peer IP Address` field. `Remote Public Key` will be changed to blank string.
On saving the settings private and public key will be assigned to record and same will be visible in `Remote Public Key` field
(Already existing functionality)

ngfw-14524 copyModify property added for wireguard-vpn tunnels

---

uvm/hier/usr/share/untangle/bin/ut-backup.sh
uvm/hier/usr/share/untangle/bin/ut-restore.sh

We are now able to backup system with the Branding logo and restoring the same
- Backup containing the Branding Logo
- Updated Branding Logo
- Logo after restore

NGFW-14504 Ability to backup and restore branding image

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_uvm.py
uvm/impl/com/untangle/uvm/UvmContextImpl.java

Q4 units were not showing unit serial number due to validation check referring to previous untangle format,
where as Arista SN looks like: CTW23050243
Removed length validation checks , added a Test caseby using bind mount bind into /sys/devices/virtual/dmi/id/product_serial and reverting back with original value.
Following is the test output
Testing steps:
Upgrade the NGFW with this PR and restart NGFW, serial number for Q4 should be visible under config about
PFA screenshot

ngfw:14414: Q4 Units do not show unit serial number under Config

---

ipsec-vpn/hier/usr/lib/python3/dist-packages/tests/test_ipsec_vpn.py
ipsec-vpn/src/com/untangle/app/ipsec_vpn/IpsecVpnPingTimer.java

Issue: 
After setting up site-to-site IPsec tunnel between two servers (Host Server and Remote Server) such that right tunnel allows any remote, Multiple unnecessary _Tunnel Connection Events_ are logged in report.
Root Cause:
When ping address was added to right tunnel ping was failing and hence _VPN Ping Timer_ functionality was failing and creating multiple events with type _UNREACHABLE_ and _RESTART_ in loop
Changes: 
Skipping ping check if right remote address is any
Added test case to verify unnecessary events are not  created.
Testing Instruction:
1. Create two NGFW on two different networks
2. Configure IPsec tunnel on on of the NGFW (Local Server) to allow any remote.
Tunnel C to D
3. Configure IPsec tunnel on Other NGFW (Remote Server)
Tunnel D to C
4. Once connection is …

ngfw-13983 skipping vpn ping for tunnels with remote any

---

wireguard-vpn/hier/usr/lib/python3/dist-packages/tests/test_wireguardvpn.py
wireguard-vpn/js/view/Tunnels.js
wireguard-vpn/src/com/untangle/app/wireguard_vpn/WireGuardVpnMonitor.java

Root Cause: In the code, stats is written in generateTunnelStatistics method of WireGuardVpnMonitor, where as healthcheck and connection closure is done in handleTunnelPingCheck method.
The handleTunnelPingCheck is not applicable to roaming clients as they neither have roaming address not pingable interval
```
if (tunnel.getPingInterval() == 0) return;
if (tunnel.getPingAddress() == null) return;
```
Above code returns which is expected behaviour. Moreover WireGuard peers don't notify each other on disconnection, only the latest handshake time is known, hence it becomes difficult to figure out whether client has disconnected or not.
Ideally we could have checked for client status before logging stats for the tunnel, due to above point , this cannot be done.
0  InBytes and 148 bytes …

ngfw-13322: WireGuard should not be monitoring roaming clients

---

uvm/js/common/util/Util.js
wireguard-vpn/js/view/Tunnels.js

**ISSUE**: In previous [PR](https://github.com/untangle/ngfw_src/pull/601) the calculation for broadcast address is failing in some scenarios. 
**FIX:** Implemented the generic range generation logic so it should work for all the subnets.
**TEST:**  Tested all the subnet mask given in https://www.subnet-calculator.com
**TEST:**
1. Go to App > WireGuard VPN > Settings.
2. Set the network space and save.
3. Go to App > WireGuard VPN > Tunnel.
4. Click "Add" to create a new tunnel. The peer IP address should be generated within the subnet IP range.
5. If the user adds a peer IP address outside of the subnet IP range or a restricted IP, an error will be displayed: "Please ensure that the entered IP address is within the specified subnet IP range."
6. For auto-assigned peer IP addresses, if …

NGFW- 13608 : Fixed IP range calculation to make it generic for all subnet mask

---

uvm/servlets/admin/config/network/MainController.js

Changes:
Updating store list if records are removed from grid store.
Testing Instructions:
1. If user enters conflicting network while adding/modifying Static route, it should show error message as shown below.
2. On deleting the conflicting address user should be able to save the settings.

ngfw-14204 updating store list if records are removed

---

captive-portal/hier/usr/share/untangle/lib/captive-portal/reports/captive-portal-admin-logout.json
captive-portal/hier/usr/share/untangle/lib/captive-portal/reports/captive-portal-idle-timeout.json
captive-portal/hier/usr/share/untangle/lib/captive-portal/reports/captive-portal-session-timeout.json
captive-portal/hier/usr/share/untangle/lib/captive-portal/reports/captive-portal-user-logout.json

ngfw-13290 : Removed auth-type default column for captive portal events

---

uvm/api/com/untangle/uvm/event/EventSettings.java
uvm/hier/usr/lib/python3/dist-packages/tests/test_alert.py
uvm/hier/usr/lib/python3/dist-packages/tests/test_alerts.py
uvm/hier/usr/lib/python3/dist-packages/tests/test_uvm.py
uvm/impl/com/untangle/uvm/EventManagerImpl.java

Changes:
1. Added code to include default _Configuration Backup Failure_ event if doesn't exists already.
2. Removed code for adding default _Critical Alert Event_ event as it was part of last upgrade

ngfw-13258 default alert for Configuration Backup Failure added

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_administration.py
uvm/hier/usr/share/untangle/bin/ut-cert-parser
uvm/impl/com/untangle/uvm/CertificateManagerImpl.java

As  per acceptance criteria handled following scenarios and test cases for following have been added.
Test case to implement upload functionality has been added.
Pem files to simulate below scenarios will be added to Jiira Ticket, and customer uploaded pem files from jiira ticket are also working with this change.
1. spaces + newline at the end of the each line
2. DOS style CRLF at end of each line
3. spaces +  DOS style CRLF at end of each line
Earlier in case of failure, nothing was shown on UI, there was a change required in way errorMessage returned to UI
Now the Error message will be shown as PFA
in ut-cert-parser, try except block is added , if file is not parseable by pem module, above default behavior is shown.
Following is test case output, all tests are passing

ngfw-13953: Strip trailing spaces in uploaded certificates

---

uvm/servlets/admin/config/network/Interface.js

According to testing review, user was able to save alias with reserved IP.
I am using `SelectionModel` to get the selected row in the alias grid. 
When we add alias, somehow `SelectionModel` is not able to pick the row and hence value of `this.up("ungrid").getSelectionModel().getSelection()[0]` is `undefined`
Added a condition such that if value of above expression is `undefined` then use default value of `staticPrefix` i.e. 24.
As we are facing this issue only when we add new alias it should not be a problem to use default value as 24.
We are using same default value (24) for empty row.

ngfw-13538 handling initial condition for add alias

---

web-filter-base/src/com/untangle/app/web_filter/DecisionEngine.java
web-filter/hier/usr/lib/python3/dist-packages/tests/test_web_filter.py

Root Cause:
Earlier code was just checking for Flagged and passing the rule, made changes to check both flagged and unflagged,
In case of Flagged added event to flagged events.
Added test case to simulate the scenario and it is passing.
Testing Steps:
For existing setup, got to Apps-> WebFilter
1. Enable Social Networking  category in Group Productivity in categories,
2. Enable block and flag check box, at this point , verify (www.facebook.com is blocked by web filter)
3.  Add a Rule from rules tab, with condition as Web Filter category and Value as Social Networking, enable flag check box, action as pass , verify (www.facebook.com is not blocked by web filter and accessible)
4. In step 3 go back and removed flagged checked option from above rule, verify (www.facebook.com is blocked by …

ngfw-13254: Web Filter Unflagged Pass Rule No Trigger

---

intrusion-prevention/hier/usr/lib/python3/dist-packages/tests/test_intrusion_prevention.py
intrusion-prevention/hier/usr/share/untangle/bin/intrusion-prevention-get-updates
intrusion-prevention/src/com/untangle/app/intrusion_prevention/IntrusionPreventionApp.java
intrusion-prevention/src/com/untangle/app/intrusion_prevention/IntrusionPreventionSettings.java

**Request:**  We should stop setting hash value in settings file while updating the signature, as there is not significant use of those values.
**FIX:** Removed all the relevant references to MD5 value generation.
**TEST:**
- Run the ngfw build 
- Added new rule, signature in IPS and checked the setting file generation. It should not contain below fileds: 
classificationMd5sum, defaultsMd5sum and variablesMd5sumq
Added unit test:
1. Make copies of current files (copy to /tmp):
Current settings file
/usr/share/untangle-suricata-config/current/templates/defaults.js
/usr/share/untangle-suricata-config/current/rules/classification.config
/etc/suricata/suricata.yaml
2. Make modifications:
/usr/share/untangle-suricata-config/current/templates/defaults.js
Safe value to change: SYSTEM_MEMORY …

 NGFW-14518 : Removing the code to set hash values in IPS settings on signature update

---

ipsec-vpn/js/view/VpnConfig.js

For IPSec VPN virtual config, we are now restricting address pool network bits to <= 30 for L2TP, XAuth, IKEv2.
For CIDR: `10.1.0.15/30`, `/etc/xl2tpd/xl2tpd.conf` gets,
```
[lns default]
ip range = 10.1.0.14 - 10.1.0.14
local ip = 10.1.0.13
```
For CIDR: `10.1.0.15/29`, `/etc/xl2tpd/xl2tpd.conf` gets,
```
[lns default]
ip range = 10.1.0.10 - 10.1.0.14
local ip = 10.1.0.9
```

NGFW-14307 IPsec VPN- Restricting network bits to <= 30 for L2TP, XAuth, IKEv2

---

virus-blocker-lite/hier/usr/share/untangle/lib/virus-blocker-lite/reports/top-ftp-clients.json
virus-blocker-lite/hier/usr/share/untangle/lib/virus-blocker-lite/reports/top-ftp-servers.json
virus-blocker/hier/usr/share/untangle/lib/virus-blocker/reports/top-ftp-clients.json
virus-blocker/hier/usr/share/untangle/lib/virus-blocker/reports/top-ftp-servers.json

Since FTP server test.untangle.com has some issues while running the FTP tests and local FTP server is passing the blocking scenarios 
Tested this by failing the success event in  virus-blocker-base/src/com/untangle/app/virus_blocker/VirusFtpHandler.java
modifying VirusScannerResult to error always.
`result = new VirusScannerResult(false, "TestError");`
Changes Done for virus_blocker and virus_blocker_lite apps
1. Changed the table names to ftp_events and field in  FTP Top Blocked Sites to s_server_address as hostname field contains address of client from where ftp test is running. 
2. Modified description of FTP Top Blocked Sites which was referring to clients instead of sites.
Following are screenshots for virusblocker and virusblockerlite apps : Affected reports
- FTP Top Blocked …

ngfw-13845: Virus Blocker/Virus Blocker Lite FTP reports pulling from from wrong table

---

application-control/js/view/Rules.js
bandwidth-control/js/view/Rules.js
captive-portal/js/view/CaptureRules.js
firewall/js/view/Rules.js
intrusion-prevention/js/view/BypassRules.js
intrusion-prevention/js/view/IpsRules.js
policy-manager/js/view/Rules.js
ssl-inspector/js/view/Rules.js
threat-prevention/js/view/Rules.js
tunnel-vpn/js/view/Rules.js
uvm/js/common/util/Util.js
uvm/servlets/admin/app/cmp/ConditionsEditor.js
uvm/servlets/admin/app/cmp/ConditionsEditorController.js
wan-balancer/js/view/RouteRules.js
web-filter/js/view/Rules.js
web-monitor/js/view/Rules.js

Added conditional list for protocol check boxes . i.e. if app is supporting only TCP/UDP protocol then in Rules Editor, only those two check boxes should be visible.
List of the rules where change is applied
[ProtcolListChange.txt](https://github.com/untangle/ngfw_src/files/14668446/ProtcolListChange.txt)

Ngfw 13743 modify protocols condition list

---

reports/hier/usr/lib/python3/dist-packages/tests/test_reports.py
reports/src/com/untangle/app/reports/ReportsApp.java

Made change to sanityCheck method to check for getPasswordHashShadow() method which has value instead of trans_getPasswordHash.
Unit tests are already present which was failing due to above scenario, TestCase is passing.
Made a small change to revert to original report settings
Following are testcase screenshot
screen shots

Cannot give online access to existing Reports users

---

intrusion-prevention/js/MainController.js
intrusion-prevention/js/view/BypassRules.js
uvm/js/common/util/Util.js
uvm/servlets/admin/config/network/MainController.js
uvm/servlets/admin/config/network/view/BypassRules.js

If User creates a bypass rule such that one of the condition is having source address as LAN IP address then user should get a warning message.
Change Applied on Pages: 
Intrusion Prevention --> Bypass Rules
Config --> Network --> Bypass Rules
Local Testing screenshots:
If there is no such condition user should not see warning message.

Ngfw 14440 warn about bypass rules for lan addresses

---

wireguard-vpn/js/Main.js

**ISSUE:**
Copy Button for WG doesn't show with large amount of networks
**FIX:**
Adjusted alignment to ensure the copy button remains visible regardless of the fieldset contents by modifying the width of the child fieldset.
**TEST:**
1. Go to App>Wiregauard>Settings
2.  Add multiple local networks 
3. Go to  App>Wiregauard>Status , all remote networks as well as copy button should be visible regardless of the number of remote networks.
4. Go to App>Wireguard>Tunnels, click on edit button, check for local service information copy button should be visible regardless of the number of remote networks.

NGFW-13925: Fixed Copy Button alignment for WG App under 'local service information' and 'status' form

---

wireguard-vpn/js/MainController.js
wireguard-vpn/js/view/Settings.js

If user changes the Wireguard VPN settings `Listen port, Peer Address Pool and MTU` then showing a warning symbol with qtip message `Clients will need to configure their connections`.
If user re-enters current settings value then warning symbol is not shown.

ngfw-13562 show warning sysmbol with qtip message if user changes the wireguard settings

---

uvm/servlets/admin/app/cmp/ConditionsEditor.js

- Since `iptables` couldn't accept the Glob Matcher pattern for MAC address, we will accept a valid MAC address for `Client MAC Address` type of Filter Rule

NGFW-14148 Filter Rule: Restricting Client MAC address to be a valid MAC address; Glob Matcher is no longer accepted

---

uvm/api/com/untangle/uvm/event/EventSettings.java
uvm/api/com/untangle/uvm/event/SyslogRule.java
uvm/api/com/untangle/uvm/event/SyslogServer.java
uvm/hier/usr/lib/python3/dist-packages/tests/test_syslog.py
uvm/impl/com/untangle/uvm/EventManagerImpl.java
uvm/impl/com/untangle/uvm/SyslogManagerImpl.java

AS per requirement Criteria
Added SyslogServer list in EventSettings default server will have tag (uvm[0] , others will have uvm-to-server-ip)
Added Syslogserver ID list in SyslogRule
Modified rules to evaluate and send logs to multiple logservers
Added iterative syslog remote configuration in syslog conf file
```
if $msg startswith ' <tag>' then @192.168.25.51:514
& stop
```
Added testcase covering scenarios
1. Enabling syslog
2. Disabling syslog
3. Adding multiple syslog
4. Adding/Deleting multiple syslog
Following are screenshots of syslog conifugration
TestCases

ngfw-14554: multiple syslog update settings

---

uvm/servlets/admin/app/cmp/ConditionsEditorController.js

**ISSUE:**
‘Is Not’ operator does not work for Protocol condition with multiple value
**FIX:**
IPtable itself does not allow the invert operator with multiple values other than Ports, so added the alert while choosing "is NOT" operator in filter-rule conditions.
**TEST:**
Alert should be pop-up in case of all the condition except DESTINATION PORT.

NGFW-14149: ‘Is Not’ operator does not work for Protocol condition with multiple value

---

uvm/api/com/untangle/uvm/app/IPMatcher.java
uvm/servlets/admin/app/overrides/form/field/VTypes.js

- Added UI validation for filter rule condition: IP range must be in ascending order.
- IPMatcher.java to set min and max IP addresses in case of range in ascending order.

NGFW-14146 UI validation for descending order for filter condition IP range

---

uvm/js/common/ungrid/GridColumns.js
uvm/js/common/util/Util.js
uvm/servlets/admin/app/overrides/form/CheckboxGroup.js
uvm/servlets/admin/config/events/MainController.js
uvm/servlets/admin/config/events/MainModel.js
uvm/servlets/admin/config/events/view/Syslog.js

Enable adding multiple syslog servers by adding grid. Allowing user to use these servers in syslog rules.
[Design Document](https://awakesecurity.atlassian.net/wiki/spaces/ngfw/pages/2372993027/Design+Multiple+Remote+Syslog+Events)
Changes on Config --> Events --> Syslog Page
1. Removed `Remote Syslog Configuration` container.
2. Added Syslog Servers Grid where user can add syslog using `add` button.
3. Added editor to enable user to edit syslog server configuration.
4. Each server will be assigned a unique `Server Id` and it can not be reordered.
5. `tag` value for each syslog server (except Remote Syslog server `tag=uvm[0]`) will be auto populated in format `uvm-to-%host%`
Syslog Servers object in `event.js` file
6. Removed `Remote Syslog` column and editor field from Syslog Rules Grid …

Ngfw 14555 add syslog server grid and update syslog rules grid

---

uvm/js/common/util/Util.js

**ISSUE:** 
Local network should not be validated against network registry.
**FIXED:**
Updated logic to validate only Network Space in WG settings against network Registry
**TEST:**
- Have two LANs configured in Config → Network → Interfaces.
- Under WireGuard → Settings, remove one of them from the Local Networks table (may need to remove the Wireguard app and reinstall for both networks to appear in table). Save.
- Now test below scenarios.
1.  Try to assign same Ip address under Network space , it should show address pool conflict.
2. Try to assign deleted IP address again in local network, it should not show any conflict.
3. Try to assign the IP address already present in local network pool, it should show address pool conflict.
- Go to WG -> Tunnels
- Add new tunnel try to add same …

NGFW-14533: Updated logic validate only network space in WG against network Registry

---

uvm/api/com/untangle/uvm/event/SyslogServer.java
uvm/hier/usr/lib/python3/dist-packages/tests/test_syslog.py
uvm/impl/com/untangle/uvm/EventManagerImpl.java

Added description field for syslog server. Modified test case to check for description field.
Following is screenshot for description field
Testcases Output

ngfw-14567: Add description field to syslogserver (Backend changes)

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_syslog.py
uvm/impl/com/untangle/uvm/EventManagerImpl.java
uvm/impl/com/untangle/uvm/SyslogManagerImpl.java

This Pr covers following scenarios, along with changes for Enable Syslog from backend
1. If before Upgrade syslog server is enabled then all the rules will be assigned to that particular syslog server after upgrade, and a server in syslog server list
2. If Before Upgrade syslog server is disabled then all the rules will be assigned empty integer syslog server list, along with empty syslog
server list.
In both the cases step 2 and 3, Enable syslog field after upgrade , will not affect syslog servers. After UI changes Enable syslog field won't be visible in UI.
Modified testcases to cover scenario 1 above rules should be assigned syslog server in case before syslog is enabled and configured.
Modified Test cases Passing

ngfw-14565: Remove the "Enable Syslog" (Backend changes)

---

uvm/servlets/admin/config/events/MainController.js
uvm/servlets/admin/config/events/MainModel.js
uvm/servlets/admin/config/events/view/Syslog.js

**Changes:**
1. For `Syslog Servers` grid `serverId` comes from the back-end during `setSettings`.  Therefore it will not be available for `Syslog Rules` until settings have been saved.  Therefore after a syslog server has been added/edited/deleted, **disabled** the `Syslog Rules` grid with a message `Save the New/Modified/Deleted records in Syslog Server grid to enable Syslog Rules`.
2. **Reserved** the `Syslog Server` if any of `Syslog Rule` is using it.
Local Testing Screenshots.
If new Syslog Server is added or existing edited/marked for delete then disabling the Syslog Rules Grid.
------------------------
On clicking on save button, syslog rules grid is enabled.
------------------------
If any of newly added or existing syslog rule is using syslog server then mark it as reserved and …

ngfw-14564 handling syslog server and rules update and dataChange events

---

uvm/servlets/admin/config/events/MainController.js
uvm/servlets/admin/config/events/view/Syslog.js

1. Added **Description column and editor field** in Syslog server grid.
2. Added validator for description editor field to not allow duplicate values.
3. In Syslog Rules record editor - Syslog servers field will be a check-box group with syslog **description as label**. On hover syslog **host** will be shown in qtip message.
4. If Syslog server is **disabled** then respective checkbox in rule editor will be marked as **read only** with qtip message **Enable the server with host {host}**
Local Testing Screenshots
Description Column
-------------------------
Description Editor
-------------------------
On Syslog Server Add
------------------------
After saving server description is correctly populated in events.js file
-------------------------
Syslog rule editor - Syslog servers …

Ngfw 14567 add description field syslog servers

---

uvm/servlets/admin/sass/base.scss

**ISSUE:**  When the content is overflow, scroll is braking while coming to top of the window, and instead will loop over the bottom. The cause of this issue is ExtJs is internally creating x-scroller-spacer  with style transform : translate3d(), which is not allowing grid, style transform: translate3d() , to fetch correct value and loop is formed.
**Fixed:** Override ExtJs x-scroller-spacer style.
**Test:**
Go to below apps tab and Scroll down to the bottom of a window with a scroll bar. Then, attempt to scroll to top quickly. You will  reach the top of the window.
- Intrusion Prevention > Signatures
- Web Monitor > Categories
- Web Filter > Categories
- Report > All Reports
Tested It for all below resolutions and browser window.

NGFW-14382: Fixed vertical scrolling issue

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_network.py

Hardcoded value for the mac addresss changed to dynamic MAC Address

ngfw:14588 - test case changed for MAC Address

---

directory-connector/src/com/untangle/app/directory_connector/GroupManager.java

- Fixed AD get groups when the first AD is non functional and second one is functional.
- Issue was we were doing `return` if we encounter a connection failure. Instead we must skip that AD server.

NGFW-13892 Fixed AD get groups issue

---

uvm/api/com/untangle/uvm/SystemManager.java
uvm/impl/com/untangle/uvm/NotificationManagerImpl.java
uvm/impl/com/untangle/uvm/SystemManagerImpl.java
uvm/servlets/admin/config/upgrade/MainController.js
uvm/servlets/admin/config/upgrade/view/Upgrade.js

**Issues:** There have been a few customers that had issues with their boxes on upgrade attempt due to low amount of disk space. 
**Fix:** Added provision to disallow upgrade by disabling the upgrade now button and showing the error on UI.
**While analysing the issue found the issue in logic written to calculate the diskusage in NotificationManagerImpl, fixed the same.**
**Test:** 
**-  If no upgrade available then UI will be shown as below:**
**-  If upgrade available without any configuration issues then only Upgrade button will be visible:**
**-  If upgrade available with any configuration issues then Upgrade button will be disable any error will get display on UI:**

NGFW-14309: Added functionality to disallow upgrades if the disk space is low

---

tunnel-vpn/js/MainController.js
tunnel-vpn/js/view/Tunnels.js

Changes:
Switched the conditions for `hidden` and `disabled` properties of `Username` and `Password` fields to enable/disable Done button according to form validation.
`Username` and `Password` fields will be hidden until `Provider` field is selected from drop-down.
`Username` and `Password` filed will be disabled for providers which don't require authentication (i.e. `provider.auth = false`)
Local Testing

ngfw-14578 TunnelVPN Tunnel Record Editor Done Button bug Resolved

---

bandwidth-control/hier/usr/lib/python3/dist-packages/tests/test_bandwidth_control.py
bandwidth-control/js/MainController.js
bandwidth-control/src/com/untangle/app/bandwidth_control/BandwidthControlApp.java
uvm/servlets/admin/app/Application.js
uvm/servlets/admin/app/cmp/AppState.js

If qosEnabled is disabled and the user enables/power-on the bandwidth-control app, then qosEnabled will be enabled 
Test case result :

ngfw : 14188 - qosEnabled changes for bandwidth-control

---

openvpn/js/MainController.js
openvpn/js/view/Server.js
uvm/js/common/ungrid/GridController.js
uvm/js/common/util/Util.js
wireguard-vpn/js/view/Tunnels.js

**ISSUE:**  This PR resolves 2 issues:
1. Import function has no validation.
2. RemoteNetwork validator should be handled at UI level so save button should not get disabled.
**FIX:**
1. Added all validator at field level to validate data at import, edit and add operation.
2. Implemented validator for RemoteNetwork field to validate IPs should not insect each other.
**TEST:**  
**1. OpenVPN -> Server -> Remote Clients** 
-   Create a new client record with name already existed it should show error.
- Create a new record or try to edit a record with Type:Network and try to put the invalid IP which intersect with already exited remote network in other records, It will show error.
- Try to edit record of Type:Network and put the already existed value in same row, it will show error.
- Try to …

NGFW-14584/NGFW-14589/NGFW-14585 : Import validation for OpenVPN grids/IPSec VPN and Validation added for OpenVPN Remote Network field

---

docs/EventsDescriptionExtensionImpl.java
docs/EventsDocumentationExtensionImpl.java
docs/reports-generate-docs-column-names.py
docs/reports-generate-docs-db-schema.py
reports/hier/usr/lib/python3/dist-packages/reports/untangle_vm.py
reports/hier/usr/lib/python3/dist-packages/tests/test_reports.py
reports/hier/usr/share/untangle/bin/reports-reinitialize-database.sh
reports/src/com/untangle/app/reports/ReportsApp.java
reports/src/com/untangle/app/reports/ReportsManagerImpl.java
uvm/api/com/untangle/uvm/OperationsEvent.java
uvm/api/com/untangle/uvm/SettingsManager.java
uvm/hier/usr/share/untangle/lib/untangle-vm/events/classFields.json
uvm/hier/usr/share/untangle/lib/untangle-vm/reports/administration-operations.json
uvm/impl/com/untangle/uvm/SettingsManagerImpl.java
uvm/js/common/util/_Map.js

Following changes done for the PR
- Create a new system_operations table.  Model this after the existing settings_changes table except instead of a “settings_file” column, add a new text-type column for “operation”.
- Create a new “All Operations” report modeled after the existing “All Settings Changes” report.  It should just display the operation.
- Create a new Operations log event modelled after SettingsChangesEvent will be created when operations like the Delete All Reports Data action is called.  
- For this case, use an operation value of “delete all reports data”.
- ATS should verify that after the action is executed, a query of this table has the expected event.
Testing steps:
1. go to apps/reports/data
2. click on delete all reports data
3. click on yes to continue
4. after …

NGFW-13867: Add record of purges of the database to admin all settings changes report.

---

threat-prevention/src/com/untangle/app/threat-prevention/ThreatPreventionHttpsSniHandler.java
web-filter-base/src/com/untangle/app/web_filter/WebFilterHttpsSniHandler.java

While trying to process the traffic, domain for **AnyDesk** connection is `anynet relay`. 
We check for URL validity using java.net.URI. 
`http://anynet relay/` is not a valid Url and hence exception was thrown.
Using `java.net.URLEncoder` to avoid this and using encoded domain.

Ngfw 13782 threat prevention anynet relay domain issue

---

uvm/hier/etc/cron.daily/untangle-email-cleaner
uvm/hier/usr/lib/python3/dist-packages/tests/test_uvm.py

Acceptance Criteria
Add cron script to delete the emails which are having TO or FROM the Outgoing Email FROM_EMAIL address from email tab.
Added Testcase for the scenario, which implements following points
1. Modify FROM_EMAIL to non deliverable mail
2. Send emails to non deliverable email, note the count of messages using exim -bpc
3. Run cron script explicitly to delete the emails which are having TO or FROM the Outgoing Email FROM_EMAIL address.
4. Verify the count of messages should decrease after cron script is run
Please note that queue is run periodically to send messages, there is retry mechanism if message delivery fails and during message being delivered, it cannot be deleted as the exim server locks the message or process. …

ngfw-14580: Automatic queue email queue clearing

---

captive-portal/hier/usr/lib/python3/dist-packages/tests/test_captive_portal.py
captive-portal/src/com/untangle/app/captive_portal/CaptivePortalSSLEngine.java

- Unwrap method of Captive Portal SSLEngine now does not come out of the loop if there is no data. This is to support TLS 1.2 handshake flow.
- Change does not affect TLS 1.3 handshake flow.
- Added test case for TLS 1.2.
```
== testing captive-portal ==
Test success : test_073_check_secure_redirect_enabled_with_tls1_2 [0.8s] 
== testing captive-portal [31.6s] ==
Tests complete. [31.6 seconds]
1 passed, 0 skipped, 0 failed
Total          :    1
Passed         :    1
Skipped        :    0
Passed/Skipped :    1 [100.00%]
Failed         :    0 [  0.00%]
```
- Verified for TLS 1.3 and TLS 1.2 that the Captive Portal page is prompted.
- Verified that the authentication with google, microsoft and facebook works as part of the earlier ticket where this change was made …

Ngfw 14561 Captive Portal fix for TLS 1.2 handshake

---

buildtools/jars.rb
directory-connector/src/com/untangle/app/directory_connector/RadiusLdapAdapter.java
downloads/Makefile

**ISSUE:**  The previous version of bcprov-jdk15-1.44.jar assigned with jradius-client-1.1.4-release lib has several CVEs associated with it.
**ANALYSIS:** While investigating got to know that support for [jradius](https://github.com/coova/jradius) (last version present in maven is[ 1.1.5](https://mvnrepository.com/artifact/com.github.coova.jradius/jradius-client)) has been stopped since long ago so as per discussion with team created new repo for jradius : https://github.com/AristaKB/jradius/tree/main which will include all the latest non-vulnerable dependencies in it and generated the zip package for the same to use in ngfw.
**FIX:** updated the version of jradius packages accordingly.
**TEST:**
Run the below test class as these are using these libraries:
1- Captive-Portal …

NGFW-13987: Update Vulnerable Transitive dependencies of Jradius package

---

uvm/hier/usr/share/untangle/bin/ut-uvm-device-status.sh

**Issue:** On restoring backup of four physical interfaces (i.e. eth0, eth1, eth2, eth3) on device with two interfaces, system did not show NIC status.
**Fix:**  Added a condition in `ut-uvm-device-status.sh` file (used to get Connection status of interfaces) such that if `/sys/class/net/${t_intf}/mtu` file not found then `mtu` value will be by default `1500`
**Local Testing:** 
1. Added four adapters to create four physical interfaces.
2. Taking backup of configuration settings
3. Removed two physical interfaces from device
4. Restoring backup settings
It would give status output as given below
> {
"javaClass": "java.util.LinkedList",
"list": [
{
"javaClass": "com.untangle.uvm.network.DeviceStatus",
"deviceName": "eth0",
"connected": "CONNECTED",
"mbit": 1000,
"duplex": "FULL_DUPLEX", …

ngfw-14612 setting default mtu while getting nic status

---

uvm/servlets/admin/app/overrides/form/field/VTypes.js

We are now allowing comma separated list of integers that contain spaces in custom rule condition.
Earlier, no spaces were allowed in the list.
Backend also trims the value 
IntMatcher.java
```
private void initialize(String matcher)
{
matcher = matcher.toLowerCase().trim().replaceAll("\\s", "");
this.matcher = matcher;
```
And `iptables` translated the rule, 
```
[root @ arista] ~ # iptables -S | grep 30072
-A access-rules -p udp -m comment --comment "Rule #25" -m multiport --dports 30072,30073,30074 -j RETURN
-A access-rules -p tcp -m comment --comment "Rule #25" -m multiport --dports 30072,30073,30074 -j RETURN
```
Hence no backend change was required.

NGFW-14609 Allowing comma separated integers with spaces for custom rule condition

---

buildtools/jars.rb
downloads/Makefile

Previous version that we are using is 8.5.83.
After checking the [documentation](https://tomcat.apache.org/tomcat-10.1-doc/RELEASE-NOTES.txt) got to know that after [10 version onwards](https://tomcat.apache.org/download-10.cgi) they have update the servletAPi version to  [jakarta.servlet](https://mvnrepository.com/artifact/jakarta.servlet) » [jakarta.servlet-api](https://mvnrepository.com/artifact/jakarta.servlet/jakarta.servlet-api) » 6.0.0 which now comes under jakarta.
As we are using multiple other jars which is still dependent on [javax.servlet](https://mvnrepository.com/artifact/javax.servlet) » [servlet-api](https://mvnrepository.com/artifact/javax.servlet/servlet-api), (such as [Jabsorb]
(https://github.com/AristaKB/jabsorb/tree/main/lib-ext), …

NGFW-13993: Updated apache-tomcat to latest compatible version i.e 9.0.89

---

uvm/hier/usr/share/untangle/conf/untangle-vm.conf

Fixed below warnings from console.log
```
Nov  8 14:50:06 arista uvmconsole: Nov 08, 2022 2:50:06 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesObjectStreamClassCaches
Nov  8 14:50:06 arista uvmconsole: WARNING: When running on Java 9 or later you need to add "--add-opens=java.base/java.io=ALL-UNNAMED" to the JVM command line arguments to enable ObjectStream cache memory leak protection. Alternatively, you can suppress this warning by disabling ObjectStream class cache memory leak protection.
Nov  8 14:50:06 arista uvmconsole: Nov 08, 2022 2:50:06 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalsForLeaks
Nov  8 14:50:06 arista uvmconsole: WARNING: When running on Java 9 or later you need to add "--add-opens=java.base/java.lang=ALL-UNNAMED" to the …
```

NGFW-14227 Exposed java.lang, java.io and sun.rmi.transport packages

---

openvpn/src/com/untangle/app/openvpn/OpenVpnAppImpl.java

**ISSUE:**  : When trying to connect two NGFW's with OpenVPN site to site connection using user/pass authentication with local directory the server never shows connected while the client does and traffic does not pass.
The issue occurs because when configuring the remote server, the file uploads and settings are immediately set, causing a system restart. However, for authentication with username and password, after uploading the file, manual configuration is needed. Since the app restart logic lacks a condition for remote server updates, these changes aren't reflected, resulting in no connection status being shown at server end.
**FIXED:** Updated restart logic by adding conditions for remote server update.
**TEST:** 
1. Configure OpenVPN for user/pass authentication
2. Create site to …

NGFW-13424: Fixed OpenVPN Site to Site user/pass authentication

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_network.py
uvm/hier/usr/share/untangle/bin/network-status.sh
uvm/hier/usr/share/untangle/bin/ut-routedump.sh
uvm/hier/usr/share/untangle/bin/ut-upgrade.py
uvm/servlets/admin/config/network/MainController.js

Inorder to solve dependency issue of sync settings on quagga, did the following
Quagga  dependency is to be removed from /var/lib/dpkg/status from sync settings Depends definition.
This is done to avoid untangle-sync-settings and its dependant packages being removed when installing frr. 
During upgrade frr has to be installed manually (handled in script),  later on check is added to stop frr from getting installed again
Added testcase for BGP routing with two NGFW, there is a test case to check status of configuration for BGP and OSPF it is running fine.

ngfw-14616: Add Service files for zebra, ospf and bgp daemons

---

intrusion-prevention/hier/usr/lib/python3/dist-packages/tests/test_intrusion_prevention.py
openvpn/hier/usr/lib/python3/dist-packages/tests/test_openvpn.py
reports/hier/usr/lib/python3/dist-packages/tests/test_reports.py
uvm/hier/usr/lib/python3/dist-packages/tests/test_network.py
uvm/hier/usr/lib/python3/dist-packages/tests/test_uvm.py

**ISSUE:** 
Some of the recent tests do not have a numerical component to the title.   All tests should have a numerical component so they are run in a specific order.
**Fixed:** Updated testcases name as per naming convention, so they would run in a specific order.
**TEST:**
Run below test cases:
1. test_201_settings_changes
2. test_041_createDisableClientVPNTunnel
3. test_111_data_retention_days
4. test_112_data_retention_hours
5. test_148_invert_iptables_command
6. test_304_email_cleaner
7. test_307_geo_ip_address

NGFW-14639: Updated the test case name as per ngfw naming convention

---

web-filter/hier/usr/lib/python3/dist-packages/tests/test_web_filter.py

**ISSUE**: test_700_safe_search_enabled is failing and Enforce safe search on popular search engines is not working for Yahoo/bing while hitting through wget.
**ANALYSIS:**
On UI the code is working as expected for bad terms while the safe search is enforced by webfilter.
[UI enforcing safesearch using ngfw](https://github.com/untangle/ngfw_src/assets/155290371/d6e3e553-eb43-49ba-acf9-45cee2d02582)
Only the test cases are failing as it usage incorrect URL.The URL we are sending as part of testing, somehow would not allow to fetch the appended safe search param for specific sites.
**FIX:** updated URL in case of safe search enforced is true.
**TEST:**
Can be test in 2 ways option one through UI and 2nd through testcase.
**1 - Through UI:**
- On windows client end disable default safe …

NGFW-14062/ NGFW-14640: Enforce safe search on popular search engines is not working for Yahoo and Bing test is failing 

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_vulnerabilities.py

Added `test_020_mod_apache_status` test case
```
test_020_mod_apache_status start [2024-06-05T20:23:38]
test_020_mod_apache_status (tests.test_vulnerabilities.VulnerabilitiesTests) ... build_curl_command: curl --silent --insecure --location --connect-timeout 10 --max-time 20 -s -o /dev/null -w "%{http_code}" 'http://192.168.2.1:80//server-status'
ok
----------------------------------------------------------------------
Ran 1 test in 0.047s
OK
test_020_mod_apache_status end   [2024-06-05T20:23:38]
======================================================================
== testing vulnerabilities ==
Test success : test_020_mod_apache_status [0.0s] 
== testing vulnerabilities [0.5s] ==
Tests complete. [0.5 seconds]
1 passed, 0 skipped, 0 failed
Total          :    1
Passed         :    1 …
```

NGFW-14626 Added apache status mod vulnerability test case

---

uvm/servlets/admin/app/view/extra/Users.js

The Import/Export option is removed from the grid as it's not needed.

ngfw:14635 - Import/export option removed from users grid

---

uvm/servlets/admin/app/view/extra/Devices.js

Import/Export option removed from devices grid as it's not required.

ngfw : 14634 - Import/Export option removed from devices grid

---

uvm/hier/usr/lib/python3/dist-packages/tests/global_functions.py

The issue is with print(events) statement getting logged in /tmp/unittest.log for the test (test_100_blocked_queue) during get_wait_for_events method call which as 60 retries
As per the test there are 60  retries while finding the event in (get_wait_for_events method)  for each print(events) statement 12k space is getting consumed, local tests have shown 108k usage, since test bed has complex configuration retries before success, it must be consuming more.
Fix: Removed the print statement, 
Output before fix:
unittest.log  size 148K
Output after  adding removing print(events)  fix
unittest.log size is not increasing beyond 12k.

NGFW-14638: Tests which fill the disk do not clean up after end of test.

---

web-filter-base/src/com/untangle/app/web_filter/DecisionEngine.java
web-filter-base/src/com/untangle/app/web_filter/SearchEngine.java
web-filter-base/src/com/untangle/app/web_filter/WebFilterDecisionEngine.java

**ISSUE:**    Youtube allows you to "retry" and access blocked search results.
**ROOT_CAUSE:** Youtube retry URL does not contain the search term hence does not cause any blockage and blocked term can be accessed while retrying.
**FIX:** The search term is present in request payload hence adding one additional condition to fetch the term through referer and match the pattern.
**TESTING:**
-  You will get the option of retry for the blocked term only if you use the default root_cert.
1.           Configure SSL Inspector with default root cert.
2.           Configure Web Filter with search term blocks
3.           Verify Safe Search is on in Web Filter
4.           Install SSL Certificate on test computer behind NGFW
5.           Test blocks on youtube.com search
6.           When presented …

NGFW-13774: Youtube retry option bypasses blocked search terms

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_network.py

**ISSUE:** While running network test suite getting below error
```
Verify we can get vendors for the mac addresses ... A little error:  {'msg': 'Invalid security nonce', 'code': 595}
ERROR
======================================================================
ERROR: test_705_mac_address_vendor_lookup_list (tests.test_network.NetworkTests)
Verify we can get vendors for the mac addresses
Traceback (most recent call last):
File "/usr/lib//python3/dist-packages/tests/test_network.py", line 2611, in test_705_mac_address_vendor_lookup_list
deviceStatus = uvmContext.networkManager().getDeviceStatus()
File "/usr/lib//python3/dist-packages/jsonrpc/proxy.py", line 81, in call
raise JSONRPCException(resp['error'])
jsonrpc.proxy.JSONRPCException
```
**FIXED:** Fixed the uvmContext from …

NGFW-14642: Updating test case to resolve invalid security nonce issue

---

firewall/hier/usr/lib/python3/dist-packages/tests/test_firewall.py
uvm/hier/usr/lib/python3/dist-packages/tests/common.py
uvm/hier/usr/lib/python3/dist-packages/tests/test_email.py

**Issue:** Restarting UVM test cases causes test failures because it changes the nonce ID for UvmContext. To maintain consistent nonce IDs, we are now retrieving the current reference of UvmContext from global_functions.
**Additional Fix:**
In the EMAIL - test_100_blocked_queue, the value was not restored to its original state. It is now being set back to its original value after the test run.
cls.final_extra_tear_down() was previously called only at the app level. It has been modified to be called at the class level so that the network and email suites can reach their final versions.
**Testing:**
Run email and firewall TCs it should be passed without any failure.
`/usr/bin/runtests -t email,firewall -h <Clinet_ID>`

NGFW-14662: firewall and email test failures

---

ipsec-vpn/hier/usr/lib/python3/dist-packages/tests/test_ipsec_vpn.py
uvm/hier/usr/lib/python3/dist-packages/tests/test_network.py
web-filter-base/hier/usr/lib/python3/dist-packages/tests/test_web_filter_base.py
web-filter/hier/usr/lib/python3/dist-packages/tests/test_web_filter.py

**Testing:**
- skipped 'initial_setup exception:'
- A little error:  {'msg': 'Invalid security nonce', 'code': 595}
- Final_tear_down error.
`/usr/bin/runtests -t email,ipsec-vpn,network,web-filter,firewall -h  <Clinet_ID>
`

ngfw-14666/ ngfw-14665/ ngfw-14670 / - Fixed teardown and initial setup failiure  for web-filter, network and Ipsec-vpn

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_network.py
uvm/impl/com/untangle/uvm/NetworkManagerImpl.java

Modified test case to support frr with vrrp.
Dependant PR https://github.com/untangle/sync-settings/pull/837
PFA image
Manual Testing Configuration
- vrrp id will be same for both ngfw
- vrrp priority of primary should be greater than backup ngfw
- Add  VRRP alias as per the internal interface network and use ip which is free. Repeat the same for second ngfw.
Primary NGFW
Go to config/network/interfaces/internal/Redundant (VRRP) Configuration
Refer following image for configuration
Backup NGFW
Go to config/network/interfaces/internal/Redundant (VRRP) Configuration
Refer following image for configuration
Result: 
Primary NGFW (is Master radio button) will become green where as for secondary it will become grey
run following command in shell,
vtysh -c "show vrrp"
Master output will be as …

ngfw-14648: FRR-VRRP: Support VRRP changes with FRR

---

reports/hier/usr/lib/python3/dist-packages/tests/test_reports.py

**Testing:**
- skipped 'initial_setup exception:'
- A little error: {'msg': 'Invalid security nonce', 'code': 595}
- Final_tear_down error.
`/usr/bin/runtests -t email,reports -h  <Clinet_ID> `

ngfw-14668  - Fixed teardown and initial setup failiure for report test suite

---

intrusion-prevention/hier/usr/lib/python3/dist-packages/tests/test_intrusion_prevention.py
uvm/hier/usr/lib/python3/dist-packages/tests/test_uvm.py

Testing:
- skipped 'initial_setup exception:'
- A little error: {'msg': 'Invalid security nonce', 'code': 595}
- Final_tear_down error.
`/usr/bin/runtests -t email,uvm,intrusion-prevention -h  <Clinet_ID> `

ngfw-14669 - Fixed teardown and initial setup failiure for UVM and intrusion-prevention

---

uvm/bootstrap/com/untangle/uvm/UvmContextSelector.java
uvm/bootstrap/com/untangle/uvm/UvmExceptionPatternConverter.java
uvm/hier/usr/share/untangle/conf/log4j2.xml

The exception stacktraces were printed in following format,
This was made possible by ThrowableInterface in log4j1.x, however in logj2.x this interface is deprecated.
LogEventPatternConverter needs to implemented to achieve the same in log4j2.x.
Dependent PR
https://github.com/untangle/ngfw_pkgs/pull/109
After changes PF screenshot, Added temporary custom error for testing

ngfw-14673: Log4j Upgrade Enhancements: Analysis and implementation alternative of ThrowableRenderer

---

uvm/impl/com/untangle/uvm/NetworkManagerImpl.java

Restricting **NetworkTestExport download servlet** to download files from defined path only i.e. `/tmp/network-tests/`
Organised import statements
**Tested on local:**
If `arg1` is valid file path and is under `/tmp/network-tests/` file will be downloaded
If `arg1` is not valid file path or is not under `/tmp/network-tests/` empty response will be returned

Ngfw 14706 restrict network file download

---

uvm/servlets/admin/app/cmp/TagPicker.js

when user edits any field other than tags, then the tags value was getting changed to undefined on UI, so that issue is fixed now.

ngfw : 14651 - tag issue changes

---

reports/hier/usr/lib/python3/dist-packages/tests/test_reports.py
reports/src/com/untangle/app/reports/ReportsApp.java
uvm/api/com/untangle/uvm/util/ObjectMatcher.java

**ISSUE:** /reports/csv endpoint is quite promising and might  prone to SQL Injection.
Fixed as discuused in https://awakesecurity.atlassian.net/wiki/spaces/ngfw/pages/2554527751/Arista+NG+Firewall+Authenticated+Jabsorb+Java+Unmarshalling+Vulnerability
Also added unit test cases for the same
**Test :** 
Run the POST request with invalid argument it should failed with exception given in below screenshots.
For valid data it should return valid response.

NGFW-14711: Fixed report/csv deserializarion vulnerability

---

tunnel-vpn/hier/usr/lib/python3/dist-packages/tests/test_tunnel_vpn.py

Testing:
Run `tunnel-vpn` test suite, none of testcase should be failed and skipped with below issues.
Command: `/usr/bin/runtests -t email,tunnel-vpn -h <Clinet_ID>`

ngfw-14729 tunnel-vpn test suite failure fix

---

live-support/hier/usr/lib/python3/dist-packages/tests/test_live_support.py

Testing:
`/usr/bin/runtests -t  email,live-support -h client-IP
`skipped 'initial_setup exception:'
/usr/bin/runtests -t email,policy-manager -h <Clinet_ID>

 NGFW-14701: Fixed live-support test suite

---

reports/servlets/reports/root/index.jsp

**ISSUE:** While hitting reports (https://192.168.56.140/reports) link  and trying to logging in getting compilation error for `org.apache.log4j.helpers.AbsoluteTimeDateFormat` import statement as we have update log4j library.
**FIXED:** There is no such usage in ngfw_src library of this package, so removed the import statement.
**TEST:** 
- After fix no report UI should load properly. (https://server-ip/reports)
- Check for Console/UVM log date formate, it should ne remain same as previous log date formate.

NGFW-14710: Fixed Report Compilation Error

---

uvm/impl/com/untangle/uvm/ExecManagerImpl.java
uvm/impl/com/untangle/uvm/NetworkManagerImpl.java

There is no direct exposure for both the functions - getDeviceStatus() in NetworkManagerImpl and exec() in ExecManagerImpl, But still making deserialization process secure by apply check of tryUnmarshall.

NGFW-14712: Implementation of Vulnerability Fix for Networksettings and ExecuteManagerImpl Endpoint

---

configuration-backup/hier/usr/share/untangle/bin/configuration-backup-upload-backup.sh

- We have removed `-k` flag while uploading the backup file to the backup server.
- I tried to do the MITM but it did not work with or without `-k` option.
```
└─$ sudo bettercap -iface eth0    
bettercap v2.32.0 (built for linux amd64 with go1.22.3) [type 'help' for a list of commands]
192.168.56.0/24 > 192.168.56.157  » [07:45:02] [sys.log] [inf] gateway monitor started ...
192.168.56.0/24 > 192.168.56.157  » set dns.spoof.all true
192.168.56.0/24 > 192.168.56.157  » set dns.spoof.domains boxbackup.untangle.com
192.168.56.0/24 > 192.168.56.157  » set dns.spoof.address 192.168.56.157
192.168.56.0/24 > 192.168.56.157  » dns.spoof on
[07:45:12] [sys.log] [inf] dns.spoof boxbackup.untangle.com -> 192.168.56.157
[07:45:12] [sys.log] [inf] dns.spoof enabling forwarding.
192.168.56.0/24 > …
```

NGFW-14717 Removed insecure flag while uploading backup file

---

ad-blocker/src/com/untangle/app/ad_blocker/RulesLoader.java

There is no direct exposure for the function - loadCookieListGhostery()[This called only at time of app intitialization] in Adblocker which internally usage fromJson for deserializing CookieElement, But still making deserialization process secure by apply check of tryUnmarshall.

NGFW-14713-   Implementation of Vulnerability Fix for AdBlockerApp CookieElement Object 

---

reports/hier/usr/lib/python3/dist-packages/tests/test_reports.py
reports/src/com/untangle/app/reports/ReportEntry.java

The 1=1 condition is used in SQL injection attacks to manipulate the logic of SQL queries. Attackers can use various SQL keywords in conjunction with 1=1 to exploit vulnerabilities. Some common keywords and techniques include:
Common SQL Keywords
OR: Used to create tautologies.
Example: username' OR 1=1 --
AND: Used to bypass conditions.
Example: username' AND 1=1 --
UNION: Used to combine the results of two queries.
Example: UNION SELECT username, password FROM users
SELECT: Used to retrieve data.
Example: SELECT * FROM users WHERE '1'='1
INSERT: Used to insert data.
Example: INSERT INTO users (username, password) VALUES ('admin', 'pass'); --
UPDATE: Used to update data.
Example: UPDATE users SET password='newpass' WHERE username='admin' AND 1=1
DELETE: Used to delete data.
Example: …

NGFW-14721: Resolve additional SQL injection vulnerabilities

---

ssl-inspector/hier/usr/lib/python3/dist-packages/tests/test_ssl_inspector.py

Testing:
Run ssl-inspector  test suite, none of test cases should be failed and skipped with below issues.
**skipped 'initial_setup exception:'
Final_tear_down error.**
Command: /usr/bin/runtests -t email,ssl-inspector -h <Clinet_ID>

NGFW-14699: Fixed SSL-inspector test suite

---

intrusion-prevention/src/com/untangle/app/intrusion_prevention/IntrusionPreventionApp.java
intrusion-prevention/src/com/untangle/app/intrusion_prevention/IntrusionPreventionSuricataFastParser.java

Added addition validation before using fromJson() for deserialization of  `IntrusionPreventionEventMap` and `IntrusionPreventionRule`. 
No direct exposure of objects for which validation has been applied as it used at the time of app initiation to set defaultRule and load the event config.

NGFW-14714: Implementation of Vulnerability Fix for IPS SyncSettings and

---

virus-blocker-base/hier/usr/lib/python3/dist-packages/tests/test_virus_blocker_base.py
virus-blocker/hier/usr/lib/python3/dist-packages/tests/test_virus_blocker.py

Testing:
Run `virus-blocker` and `virus-blocker-lite` test suite, none of test cases should be failed and skipped with below issues.
Command: `/usr/bin/runtests -t email,virus-blocker -h <Clinet_ID>`

ngfw-14730 virus-blocker and virus-blocker-lite suite failure fix

---

spam-blocker-base/hier/usr/lib/python3/dist-packages/tests/test_spam_blocker_base.py
threat-prevention/hier/usr/lib/python3/dist-packages/tests/test_threat_prevention.py
uvm/hier/usr/lib/python3/dist-packages/tests/test_syslog.py

Testing:
Run ssl-inspector test suite, none of test cases should be failed and skipped with below issues.
**skipped 'initial_setup exception:'
Final_tear_down error.**
Command: /usr/bin/runtests -t email,spam-blocker,syslog,threat-prevention -h <Clinet_ID>

Ngfw 14704- Fixed spam-blocker,syslog,threat-prevention suite failures

---

web-cache/hier/usr/lib/python3/dist-packages/tests/test_web_cache.py
webroot-base/hier/usr/lib/python3/dist-packages/tests/test_webroot.py
wireguard-vpn/hier/usr/lib/python3/dist-packages/tests/test_wireguardvpn.py

Testing:
Run `wireguard-vpn` and `web-cache` test suite, none of test cases should be failed and skipped with below issues.
Commands: `/usr/bin/runtests -t email,wireguard-vpn -h <Clinet_ID>` ,  `/usr/bin/runtests -t email,web-cache -h <Clinet_ID>`

ngfw-14732 wireguard-vpn and web-cache test suite failure fix

---

shield/hier/usr/lib/python3/dist-packages/tests/test_shield.py
smtp-casing/hier/usr/lib/python3/dist-packages/tests/test_smtp.py
uvm/hier/usr/lib/python3/dist-packages/tests/test_wizard.py

Testing:
Run shield,test-smtp,test-wizard  test suite, none of test cases should be failed and skipped with below issues.
Command: /usr/bin/runtests -t email,shield,test-smtp,test-wizard -h <Clinet_ID>

ngfe-14703 : Fixed test suites failure for shield, test_smtp and test_wizard

---

openvpn/hier/usr/lib/python3/dist-packages/tests/test_openvpn.py
phish-blocker/hier/usr/lib/python3/dist-packages/tests/test_phish_blocker.py
reports/hier/usr/lib/python3/dist-packages/tests/test_reports.py

Testing:
Run openvpn,phish-blocker,reports test suite, none of test cases should be failed and skipped with below issues.
**skipped 'initial_setup exception:'
Final_tear_down error.**
`Command: /usr/bin/runtests -t  email,openvpn,phish-blocker,reports -h <Clinet_ID>`

ngfw-14702 : Fixed test suites failure for phish-blocker and open-vpn

---

uvm/servlets/admin/config/network/Interface.js
uvm/servlets/admin/config/network/MainController.js

**Changes:** Modified component query code in `validateRange` method for `rangeEnd` property of Add/Edit Interface --> DHCP Configuration.
The old query was selecting different rangeEnd property from DHCP Server Tab and hence javascript exception.
**Local Testing Screenshots:**
Verified on chrome and firefox web browsers.
----------------------------------------------
----------------------------------------------
----------------------------------------------

ngfw-14737 intfc -> dhcp configuration window UI Issue

---

uvm/bootstrap/com/untangle/uvm/UvmContextSelector.java

**Changes:** We can directly use < and > in Log4j 2.x `PatternLayout` without them being escaped. and no need to use `&lt;` and `&gt;`
**Local Testing:** 
Logs in app log file does not contain `&lt;` and `&gt;` symbols now.

ngfw-14745 log4j upgrade escape characters issue fix

---

uvm/js/common/util/Metrics.js
uvm/js/common/util/Util.js

We are no longer making any API call (especially metrics API) after server connection is lost.
This will prevent any request reaching to the sslrealy server when used from Remote Session.

NGFW-14754 Preventing metrics API call after server connection is lost

---

captive-portal/js/MainController.js
captive-portal/js/view/CaptivePage.js

**Changes:** 
1. Removed captive portal custom page configuration from UI
2. For users using custom page added a message in tab bar `Custom captive portal has been deprecated. Switch to Basic Message or Basic Logic Configuration.`
3. If user doesn't switch from Cutom page configuration and clicks on `Preview Captive Portal Page` button and does not have custom page uploaded earlier will get above message in `Missing Custom Captive Page` Message box instead of `You must upload a custom captive page to use this feature.`
- For users not using custom page for captive portal will see captive page tab as shown below.
-----------------------------------------------------------
- For users already using custom page for captive portal and having `settings.pageType == "CUSTOM"` …

ngfw-14744 removed captive portal custom page from UI

---

uvm/servlets/admin/app/controller/Global.js
uvm/servlets/admin/config/events/MainController.js

**Root Cause:** On every syslog rule grid change we are setting/updating the `reserved` property to syslog servers store records. It causes change in state of record even if we don't change any actual property of syslog server grid.
Hence in `detectChanges` method which checks for state change for all grids on page was catching the syslog servers grid every time and we were getting unsaved changes message box.
**Changes:** In `dataChange/update` handler of `syslogServer` store (`onSyslogServersGridChange`) added a condition to find if actual properties of grid record is modified or not and accordingly setting `skipDetectGridChanges` flag on the store object.
Tested below scenarios:
Added multiple syslog servers in syslog server grid, added multiple syslog rules in …

ngfw-14746 Syslog tab unsaved changes message box bug fix

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_network.py

After repeatedly running test case for n times locally , 
Two possible root causes:
A. Need to wait for check of isVRRPMaster was not present.
here Master1 represents the isVRRPMaster was enabled in second iteration
B. frr was giving error frr.service: Start request repeated too quickly. However on the box using journalctl commands for frr service, it didn’t indicate any same behavior.  Manual testing from UI shows vrrp enabled, and master status correctly.
Fix applied:
1. Added modification before frr stop, start method added reset-failed before it.
reset-failed manually clears out failed state before start , stop frr.
2. Modified the deletion of added vrrp interface, earlier network settings file was being referred,
now we are checking the interfaces on the ngfw directly. PR …

ngfw-14760: VRRP is not changing the master flag.

---

uvm/hier/usr/share/untangle/bin/ut-restore.sh

Update restore script to restore 17.1
Changed `ACCEPTED_PREVIOUS_VERSION` variable value to `17.1`
**Local Testing:** 
- On a NGFW server with `v17.0` downloaded a backup file and upgraded it to `v17.1.1`
- After upgrade is completed again took backup and upgraded NGFW to `v17.2` (with above mentioned changes)
- On `v17.2` tried to restore `v17.0` backup file and got the error message as shown below.
- When tried to restore the backup file of `v17.1.1` NGFW was able to restore it.

ngfw-14756 Update restore script to restore 17.1

---

configuration-backup/hier/usr/share/untangle/bin/configuration-backup-upload-backup.sh
configuration-backup/src/com/untangle/app/configuration_backup/ConfigurationBackupApp.java
uvm/hier/usr/lib/python3/dist-packages/tests/test_alerts.py

- Backup upload script now handles curl return status code 60 which is returned when backup upload server is 0.0.0.0.
- Also, for any other failures where script could not get the HTTP status code, we are now treating that as a failure.
- Needed to increase the test wait time to get the event.
Getting failure event with 0.0.0.0 as backup server DNS entry.
Test case:
```
== testing alerts ==
Test success : test_070_configuration_backup_fail_alert [13.7s] 
== testing alerts [14.4s] ==
Tests complete. [14.4 seconds]
1 passed, 0 skipped, 0 failed
Total          :    1
Passed         :    1
Skipped        :    0
Passed/Skipped :    1 [100.00%]
Failed         :    0 [  0.00%]
======================================================================
test_070_configuration_backup_fail_alert start …
```

NGFW-14790 Fixed backup upload failure handling for 0.0.0.0

---

wireguard-vpn/hier/usr/lib/python3/dist-packages/tests/test_wireguardvpn.py
wireguard-vpn/js/view/Settings.js
wireguard-vpn/src/com/untangle/app/wireguard_vpn/WireGuardVpnApp.java
wireguard-vpn/src/com/untangle/app/wireguard_vpn/WireGuardVpnSettings.java

**Changes:**
1. Modified DNS configuration condition for creating remote client configuration of WireGuard VPN in **sync_settings** [Pull Request](https://github.com/untangle/sync-settings/pull/912)
2. Added **DNS Search Domains** String field in page Wireguard VPN → Settings → Remote Client Configuration
3. Added `dnsSearchDomain` field in WireGuard Vpn Settings in backend to map this field
4. Setting default DNS Search domain to NGFW Domain name and configuring remote client configuration file on App initiation and NGFW Upgrade
5. Added a test case to verify search domain updated in remote client config
1. Built sync settings in local using `Ctl+Shift+B` and `(NGFW) Upload package to ISO` option.
2. On app initiation default search domain value is assigned and …

ngfw-14783-Wireguard-VPN-add-search-domains

---

captive-portal/src/com/untangle/app/captive_portal/CaptivePortalApp.java
tunnel-vpn/src/com/untangle/app/tunnel_vpn/TunnelVpnManager.java
uvm/api/com/untangle/uvm/ExecManager.java
uvm/impl/com/untangle/uvm/BackupManagerImpl.java
uvm/impl/com/untangle/uvm/CertificateManagerImpl.java
uvm/impl/com/untangle/uvm/ExecManagerImpl.java

**Changes:** 
1. Added a condition in safe command execution flow to check if `$(` is present in the command.
2. Added `execSafe` which will call exec method with safe boolean as true.
3. Using this safe execution method for below actions(requests) which were vulnerable and could be attacked with methods provided in ticket description.
- Captive portal upload and delete custom captive page (Functionality is already removed from UI but API's are active)
- Tunnel VPN upload config fie on page (Tunnel VPN --> Tunnels --> Select VPN Config File)
- Backup restore using backup file upload (Config --> System --> Restore --> Restore from file)
- Upload server certificate (Config --> Administration --> Certificates --> Upload Server Certificate)
- csr Certificate Download (Original Issue/Method …

ngfw-14800 exec vulnerability fix

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_network.py
uvm/impl/com/untangle/uvm/DeviceTableImpl.java
uvm/impl/com/untangle/uvm/NetworkManagerImpl.java

**ISSUE:** The API endpoint https://labs.untangle.com/Utility/v1/mac expects a list in the request payload. However, our code is currently sending the list as a string, which is resulting in a 400 Bad Request error.
**FIX:** Updated the implementation of the lookupMacVendor method to send the required input format for the request, which is a list of strings.
**TEST:** Written unit test to verify List of mac address, single mac address, null, empty and malformed value of mac address.
All below tests should passsed.
> /usr/bin/runtests -t network -T test_705_mac_address_vendor_lookup_list,test_706_lookup_vendor_for_mac_address_list,test_707_lookup_vendor_for_single_mac_address,test_708_lookup_vendor_for_empty_mac_address,test_709_lookup_vendor_for_null_mac_address,test_710_lookup_vendor_for_ …

NGFW-14815: Fixed Java exception coming for looking up MAC address vendor

---

tunnel-vpn/src/com/untangle/app/tunnel_vpn/TunnelVpnApp.java

**ISSUE:** Changing VPN or tunnel names does not update the names in network lists.
**ROOT CAUSE:** The network settings update mechanism only refreshes the network list when a new tunnel is added, not when an existing tunnel’s name is changed.
**FIX:** Updated the logic to ensure that network settings are synced and the network list is refreshed whenever a tunnel name is updated.
**TEST:** 
1.Install Tunnel-VPN
2.Create an VPN 
3.Check network.js settings file it should contain tunnle info under network list.
4. Now update the name of Tunnle vpn and save.
5.Check network.js settings file it should contain tunnle entry with updated name.
6. Also check uvm and tunnle logs, no error should be generated related to tunnle update.

NGFW-14809: VPN or tunnel names does not update the names in network lists

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_network.py
uvm/impl/com/untangle/uvm/NetworkManagerImpl.java
uvm/js/common/util/Converter.js
uvm/servlets/admin/app/view/extra/Devices.js
uvm/servlets/admin/app/view/extra/Hosts.js

**Changes:**
1. Added a field converter for `httpUserAgent` field on Hosts and Devices pages, so that any cross scripting can be prevented. 
This change handles the phase 1 part of attack given in POC script.
2. Added a suspicious command check in `runTroubleshooting` method for environment_arguments. This is to avoid phase 2 of attack
3. Added a test case to verify argument exploit is not possible.

ngfw-14822 Cross scripting and execEvil method vulnerability Fix 

---

directory-connector/js/view/Radius.js
reports/js/view/Data.js
uvm/js/common/ungrid/GridController.js
uvm/servlets/admin/config/local-directory/view/RadiusServer.js
uvm/servlets/admin/config/network/Interface.js
uvm/servlets/admin/config/network/view/DynamicRouting.js
uvm/servlets/setup/app/view/step/Wireless.js

**Changes:**
Added `inputType: 'password'` property in Password fields to mask value on below mentioned pages:
1. Config --> Network --> Interfaces --> Edit Interface --> Wireless Interface Configuration
2. Config --> Network --> Dynamic Routing --> OSPF --> Interface Overrides
3. Config --> Local Directory --> Radius Server
4. Directory Connector --> Radius
5. Reports --> Data (ExpertMode)
6. Grids with Change Password Functionality (e.g. Reports --> Reports Users)
7. NGFW Initial Setup --> Wireless Settings

ngfw-14821 added password mask for password fields

---

debian/untangle-vm.postinst

**ISSUE**: Brightcloud IP is not removing after update.
**FIX**: Updated the logic to remove brightcloud IP and `/etc/untangle/post-network-hook.d/010-brightcloud-fix` file after updating to latest version.
**TEST**:
**FRESH install:**
- Install ngfw 17.2
- Run command `ip addr show lo`  it should not contain 172.217.4.110/32 IP
- Also `/etc/untangle/post-network-hook.d/010-brightcloud-fix` should not present.
- Now connect to cmd server, enable device from there (It might take sometime to reflect server on cmd)
- Run command `ip addr show lo`  again, it should not contain 172.217.4.110/32 IP
**UPDATE Scenario:**
- Install 17.1.1, connect to cmd server.
- Run command `ip addr show lo`  it should contain 172.217.4.110/32 IP
- Also `/etc/untangle/post-network-hook.d/010-brightcloud-fix` is …

NGFW-14226 : Updated code to remove brightcloud ip after upgrade

---

wan-failover/hier/usr/share/untangle/bin/wan-failover-dns-test.sh

**ISSUE**
Under [NGFW-14568](https://awakesecurity.atlassian.net/browse/NGFW-14568), we have updated the way dnsmasq.conf generates server names for static DNS. The new format for Ethernet connections will appear as follows:
server=address5@device
For example:
server=192.168.25.65@eth2
Also updated PPOE DNS WAN failover test in script.
Note: For PPPoE-DNS and DHCP-DNS, we are continuing to use the previous format. The server names will reside under pppoe-upstream-dns-servers and dhcp-upstream-dns-servers, respectively. Thus, the PPPoE and DHCP server configurations will look like:
server=172.17.18.1 # uplink.1
**FIX**
The script has been updated to test WAN failover for all DNS servers.
**TEST**
Set up static, DHCP, and PPPoE WAN DNS servers one by one and perform the following steps for …

NGFW-14858: Updated Wan-failover-dns-test script as per fix under  NGFW-14568

---

ipsec-vpn/src/com/untangle/app/ipsec_vpn/IpsecVpnApp.java

**Changes:** added wait between charon daemon restart and STRONGSWAN_CONF_FILE conf file rewrite.
**Local Testing:** 
1. Setup a `IPSec tunnels` with two other NGFW's and `VPN Config` is disabled.
2. With the fix tried to restart the untangle-vm multiple times, connection was not interrupted and routes were correct.

ngfw-14844 IPSec restart routing  issue fix

---

ipsec-vpn/src/com/untangle/app/ipsec_vpn/IpsecVpnApp.java

Added a more strategic fix instead of just adding Thread.sleep() between IPSec daemon initiation and rewrite strogswan.conf implemented in PR: [IPSec restart routing issue fix](https://github.com/untangle/ngfw_src/pull/849)
Testing steps are similar to above mentioned PR.

ngfw-14844 IPSec routing issue on restart Fix

---

uvm/servlets/admin/config/network/MainController.js
uvm/servlets/admin/config/network/view/Advanced.js

**Changes:** Removing UPnP functionality with below conditions.
If `expert mode` is active then at all conditions UPnP tab will be visible and user will be able to enable or disable the functionality.
-----------------------------------------
In normal mode (i.e. without expert mode) on upgrade if user is already using UPnP functionality and it is enabled then only UPnP tab will be visible. With message `Warning: Disabling UPnP will remove this feature.`
If user disables the UPnP then tab will be hidden.
-----------------------------------------

ngfw-13995 UPnP conditional removal

---

wan-failover/hier/usr/lib/python3/dist-packages/tests/test_wan_failover.py
wan-failover/src/com/untangle/app/wan_failover/WanFailoverTester.java

Scenario:  If Wan related tests are run on Wan interface which has some connectivity issues, or is not connected (for example PPPOE interface ,  configured but not reachable or connected). The message in this case is not user friendly. Added test case for the fix.
Current Result:
`Error: ipv4: FIB table does not exist.
Dump terminated
Device "ppp0" does not exist.
ppp0: error fetching interface information: Device not found
PPPoE ppp0 Interface is down`
Something similar for all tests DNS, ARP, HTTP, PING
Expected result:
Proper message mentioning connectivity of reachability issue along with test failed message.

NGFW-14853: WAN failover with an enabled but non-active WAN interface

---

wireguard-vpn/js/view/Settings.js
wireguard-vpn/src/com/untangle/app/wireguard_vpn/WireGuardVpnMonitor.java
wireguard-vpn/src/com/untangle/app/wireguard_vpn/WireGuardVpnSettings.java

**Changes:** 
Added a checkbox on `WireGurad VPN --> Settings` Page with label `Map tunnel description to users` with below function.
1. If disabled then tunnel `description` will not be mapped to `Host Table Entry` as `hostname` and `username` field. So Captive Portal and Firewall apps will be able to capture the traffic coming though tunnel. 
2. If enabled WireGuard tunnel `description` will be mapped to `Host Table Entry` as `hostname` and `username` field. Hence Captive Portal / Firewall won't work as mentioned in ticket [NGFW-14862](https://awakesecurity.atlassian.net/browse/NGFW-14862)
[NGFW-14862]: https://awakesecurity.atlassian.net/browse/NGFW-14862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ngfw-14866 Captive Portal Not Working on Wireguard Tunnel Issue Fix

---

webroot-base/src/com/untangle/app/webroot/WebrootQuery.java

Tested the changes locally with build for ngfw and mfw openwrt. Upgraded Bctid daemon with webfilter is working as expected.
However there are dependant tickets for NGFW and MFW for following
Handling libcjson dependency and Need to change key value from catid to cat.
https://awakesecurity.atlassian.net/browse/NGFW-14884
https://awakesecurity.atlassian.net/browse/MFW-5803
These all changes should go in simultaneously.
Tested webfilter test cases all things are working fine

ngfw-14886: Need to change key value from catid to cat (bctid upgrade  36.1)

---

uvm/api/com/untangle/uvm/SystemManager.java
uvm/api/com/untangle/uvm/util/Constants.java
uvm/hier/usr/lib/python3/dist-packages/uvm/disk_health.py
uvm/hier/usr/share/untangle/bin/ut-upgrade.py
uvm/impl/com/untangle/uvm/EventManagerImpl.java
uvm/impl/com/untangle/uvm/SystemManagerImpl.java

Performing hard disk health checks using `smartct's SMART` capability before upgrade process.
1. Before every upgrade, upgrade script will call `check_smart_health` method of `disk_health.py` script.
This script checks for the root directory and runs command `smartctl -h {drive_path}` command on it.
Output is categorised in three types - pass, fail, error. 
Upgrade will be aborted only if SMART status is FAILED. Before exiting we are logging a `CriticalAlertEvent` with `component=DISK_CHECK_FAILURE`
If SMART is unsupported or any unknown error occurs then those are logged as error in result object.
If SMART status is passed upgrade will continue.
2. Added a default `AlertRule` at top for `CriticalAlertEvent` with condition `component=DISK_CHECK_FAILURE` and logs and emails enabled. so …

Ngfw 14888 hard disk checks before upgrade

---

reports/src/com/untangle/app/reports/EventWriterImpl.java
reports/src/com/untangle/app/reports/ReportsManagerImpl.java
uvm/hier/etc/untangle/startup.d/30uvm
uvm/hier/usr/share/untangle/conf/untangle-vm.conf

- Added `reports.queue_drain_threshold` and `reports.events_per_cycle` configuration flags to tune reports processing.
- Updated `partitionTableExists()` method to get database connection only when it is needed, this was the actual performance change that fixed the issue.
- `persist()` method now skips one for loop that processes events (max 50,000) and does the same work in another loop.

NGFW-14890 Reports events performance fix

---

web-filter/js/view/Advanced.js

Currently, there is no way to distinguish between ECH (Encrypted Client Hello) and non-ECH calls, as both types of Client Hello messages include the ECH extension in the packets. Therefore, we are temporarily hiding the UI changes related to this ticket until we receive ECH packets with properly encrypted records.
**Testsing:**
1. ECH enable disable button should not be visible in UI:
2. Write any web-filter rule, such as block site amazon.com. Hit the site from client it should be blocked.
3. hit any other site such as goal.com. It should work as expected.

NGFW-14894 : Hiding ECH block enable disable button

---

uvm/api/com/untangle/uvm/SystemManager.java
uvm/api/com/untangle/uvm/util/Constants.java
uvm/hier/usr/lib/python3/dist-packages/uvm/disk_health.py
uvm/hier/usr/share/untangle/bin/ut-system-mgr-helpers.sh
uvm/hier/usr/share/untangle/bin/ut-upgrade.py
uvm/impl/com/untangle/uvm/SystemManagerImpl.java
uvm/servlets/admin/config/upgrade/MainController.js
uvm/servlets/admin/config/upgrade/view/Upgrade.js

There might be a possibility of SMART health check providing false positive result. 
In that case we can’t have unconditional block for upgrade. Hence, Providing user a way to force update from UI on disk check failure.
If the SMART Disk health check fails. Auto upgrades from cron will be aborted and Critical Event will be generated as per [NGFW-14888](https://awakesecurity.atlassian.net/browse/NGFW-14888)
On upgrade page if user clicks on `Upgrade Now` button then Disk helath check will be performed.
1. If SMART failed then Warning Box will be shown to user as given below.
If user clicks on `cancel` button. Message box will close and upgrade will be cancelled.
If user clicks on `ok`  button. Upgrade will proceed skipping the Disk health check step in upgrade script.
2. For Disk check …

Ngfw 14893 Handle SMART Disk check false possitives

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_upgrade.py
uvm/hier/usr/lib/python3/dist-packages/uvm/disk_health.py

Added test cases to:
1. Check disk health check `error, pass and fail` result impact on upgrade.
2. Check disk check is skipped or not if user want's to force upgrade on disk check failure.

ngfw-14892 added test cases for disk health checks before upgrade

---

policy-manager/src/com/untangle/app/policy_manager/PolicyManagerApp.java

**ISSUE :** 
When a policy switches based on time of day, each session generates an info event, in large environments such as schools, these fill the logs which cause high disk utilization and permofrmance issue.
**FIX:**
Change the log level from info to debug.

NGFW-14889 : updated log level from info to debug

---

uvm/servlets/admin/config/network/Interface.js

Ticket -14689 
In the Safari browser, while editing a WAN interface, Radio buttons are not visible for the first time or sometimes it will take another action to refect on ui.
Here we added some css styling only for that particular component which happening due to overflow between two components (tbar).

ngfw-14689 crossbrowser safari issue resolved for interface edit option

---

openvpn/js/MainController.js
openvpn/src/com/untangle/app/openvpn/OpenVpnAppImpl.java
openvpn/src/com/untangle/app/openvpn/OpenVpnManager.java
openvpn/src/com/untangle/app/openvpn/OpenVpnRemoteServer.java
uvm/hier/usr/lib/python3/dist-packages/tests/test_uvm.py

**ISSUE:** Currently, the NGFW is storing passwords in plain text or base64 format for various features like LocalDirectory, Directory Connector, IPSec, TunnelVPN, OpenVPN, Captive Portal, and PPPoE.
**REQUIREMENT:** Passwords should not be stored in plain text in the settings.js file for any service.
**IMPLEMENTATION:** A utility method has been added in the PasswordUtil class to encrypt and decrypt passwords.
**Encryption**: We are using a binary file to encrypt the password and created a new variable to store the encrypted password. After encrypting the password, the original password is set to null to ensure it is not stored in plain text.
**Decryption**: The encrypted password is decrypted using the same binary file whenever the original password is required for authentication. …

NGFW-14839 : Password Encryption/Decryption implementation for OpenVpn Client

---

bandwidth-control/js/MainController.js
bandwidth-control/js/view/Status.js

**Issue:** We are auto enabling QoS on bandwidth control app power on. But there is a scenario where we can save invalid bandwidth control value i.e. 0 by disabling QoS. In that case we can't auto enable QoS.
**Changes:** 
To handle above scenario we are adding a message on Bandwidth Control --> Status Page.
If Bandwidth control wizard setup is done but QOS is not enabled then below warning message will be shown

ngfw-14919 Modified the warning message on QOS status if qos is disabled

---

bandwidth-control/hier/usr/lib/python3/dist-packages/tests/test_bandwidth_control.py
bandwidth-control/js/MainController.js
bandwidth-control/js/view/Status.js
bandwidth-control/src/com/untangle/app/bandwidth_control/BandwidthControlApp.java

**ISSUE:**
We are enabled QoS if Bandwidth Control is enabled even if QoS values are not set.
**FIX:** Added additional condition to verify the bandwidth values before enabling QoS, at app start.
**TEST:** Implemented unit test case to verify the same.

ngfw-14909: Fixed to code to enable QoS only for the valid QoS value

---

bandwidth-control/js/view/Status.js
uvm/impl/com/untangle/uvm/NetworkManagerImpl.java

In previous buggy environment if  QoS enabled with invalid value due to [BUG](https://awakesecurity.atlassian.net/browse/NGFW-14909), QoS should be disabled while creating new Uvmcontext.

NGFW-14917 : Enable QoS Only for non-zero bandwidth value

---

uvm/servlets/admin/app/cmp/ConditionsEditor.js

**ISSUE:** The DC AD Domain and Group field in the ruleCondition drop-down does not display group and domain from the Active Directory (AD) server. 
**FIX:** FIxed the correct method calls and written logic to ensure that the function returns the result of the asynchronous operation directly. The data should only be returned after the asynchronous call finishes to ensure the correct AD Domain and Groups are populated in the drop-down.
**TEST:**
1. Configure Directory Connector app to connect to a AD server.
2. In Web Filter go to rules and add Domain condition to a new rule.
3. Notice on the value field, the dropbox should list the Domain from the AD server.
4. Import the rules having valid domain entry, file should imported successfully.
5.  Import the rules having invalid domain entry, …

NGFW-14932:Fixed RuleCondition dropDrown field value for DC AD Group and Domain

---

uvm/servlets/admin/app/cmp/ConditionsEditor.js

**ISSUE:** The Username field in the ruleCondition drop-down does not display users from the Active Directory (AD) server. This is because the function responsible for fetching AD usernames is written within an asynchronous call, but the return statement is placed before the asynchronous operation completes, causing only the default data to be returned instead of the data from the AD server.
**FIX:**  Written logic to ensure that the function returns the result of the asynchronous operation directly. The data should only be returned after the asynchronous call finishes to ensure the correct AD usernames are populated in the drop-down.
**TEST:**
1. Configure Directory Connector app to connect to a AD server.
2. In Web Filter go to rules and add username condition to a new rule
3. Notice on …

NGFW-14918:Fixed the DC username UI load issue in rulecondition

---

ipsec-vpn/hier/usr/lib/python3/dist-packages/tests/test_ipsec_vpn.py

**Description:**
For the test test_082_any_remote_tunnel_ping, the actual settings were not being reverted after the test execution, which could affect other test environments and subsequent tests.
**Fixed:**
For the test_082_any_remote_tunnel_ping test, the modified settings are now reverted back to their original values after the test is executed. This ensures that no changes persist, preventing any potential impact on other test boxes and future tests.
Test Result on local machine:

Ngfw 14930 test fix for IPSEC settings override tests

---

reports/hier/usr/lib/python3/dist-packages/reports/sql_helper.py
reports/hier/usr/lib/python3/dist-packages/tests/test_reports.py

- Fixed `test_111_data_retention_days` and `test_112_data_retention_hours` test cases
- Generating random session_id for the unique constraint while inserting the record in DB.
- Modified `sql_helper.py` by introducing a new `cutoff_date` variable that contains only the date type value. Earlier, for `datetime` type, we were removing the time value from that date, which was ignoring the records with datetime.
Test result before fix:
```
== testing reports ==
Test success : test_010_client_is_online [2.1s] 
Test success : test_011_license_valid [0.0s] 
Test success : test_020_reinitialize_database [11.3s] 
Test skipped : test_040_remote_syslog [0.0s]
Test success : test_041_report_csv_vulnerability_via_report_user [0.8s] 
Test success : test_045_report_csv_vulnerability [1.1s] 
Test success …
```

NGFW-14934 Fixed reports data retention test cases

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_upgrade.py

Upgrade tests were failing with error `Invalid security nonce`.
Fixed the issue by referring uvmContext from global_functions.

ngfw-14945 fixing upgrade tests nonce issue

---

uvm/hier/usr/share/untangle/bin/ut-restore.sh

Update restore script to restore 17.2
Changed ACCEPTED_PREVIOUS_VERSION variable value to 17.2
Local Testing:
- On restoring version 17.1.1 backup file we get the error as given below.
- Supported backup file versions are 17.2 and 17.3. Backup files of these versions are restored.

ngfw-14938 update restore script to restore v17.2

---

uvm/hier/usr/share/untangle/bin/ut-restore.sh

Update restore script to restore 17.3
Changed ACCEPTED_PREVIOUS_VERSION variable value to 17.3
Local Testing:
On restoring version 17.2 backup file we get the error as given below.
Supported backup file versions are 17.3 and 17.4. Backup files of these versions are restored.

ngfw-14938 update restore script to restore v17.3

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_uvm.py
uvm/impl/com/untangle/uvm/LocalDirectoryImpl.java

**ISSUE:**  Not able to delete all the local users from local directory.
**FIX:** Removed the empty check from setUsers() because users can delete all entries, and the list can be empty in that case. Additionally, removed the null check since it is already handled within the loadUsersList() method.
**TEST:**
1. Navigate to Config > Local Directory > Local Users.
2. Add multiple user with a valid email address and save.
3. Delete single user and save.
4. Check user should deleted successfully.
5. Now delete all users and save.
6. Check all user should deleted successfully.

NGFW-14940:Fixed local user deletion issue

---

configuration-backup/src/com/untangle/app/configuration_backup/ConfigurationBackupApp.java
uvm/api/com/untangle/uvm/util/Constants.java
uvm/impl/com/untangle/uvm/BackupManagerImpl.java
uvm/impl/com/untangle/uvm/ConfigManagerImpl.java

- Backup filename is generated on the basis on hostname and domain. A hostname containing spaces was causing issue while identifying if the backup succeeded or not. We are now generating the backup file with name that does not contain white spaces.
- Test case result
```
== testing configuration-backup ==
Test success : test_010_clientIsOnline [1.3s] 
Test success : test_011_license_valid [0.0s] 
Test success : test_020_backupNow [17.8s] 
Test success : test_030_verifyBackupCronjob [0.0s] 
Test success : test_140_compare_cloud_backup [21.1s] 
== testing configuration-backup [41.4s] ==
Tests complete. [41.4 seconds]
5 passed, 0 skipped, 0 failed
Total          :    5
Passed         :    5
Skipped        :    0
Passed/Skipped :    5 [100.00%]
Failed         :    0 [  0.00%]

NGFW-14925 Fixed backup upload report failure when hostname contains white spaces

---

clam-base/src/com/untangle/app/clam/ClamClient.java
phish-blocker/hier/usr/lib/python3/dist-packages/tests/test_phish_blocker.py
phish-blocker/src/com/untangle/app/phish_blocker/PhishBlockerApp.java
uvm/hier/usr/lib/python3/dist-packages/tests/global_functions.py

Changes
1. Modified code to use single socket for communication
2. There are 3 services to be stopped, daemon, socket, freshclam. Starting daemon should start socket automatically
3. Added testcase for verifying socket and its communication with positive and negative test case.
All Virus Blocker lite test case are passing

NGFW-14970: API Changes for clamav upgrade support

---

uvm/servlets/admin/config/network/Interface.js

**Changes:** Enabling null selection for `DHCP Configuration --> Netmask Override Field`

ngfw-14961 enable null selection for DHCP netmask override field

---

uvm/servlets/admin/config/network/view/DhcpServer.js

**Changes:** Added validation for `Config --> Network --> DHCP Server --> Maximum Leases` field

ngfw-14968 Added validation for maximum leases field

---

ipsec-vpn/js/view/IpsecTunnels.js

- Fixed the case when an already created IPsec tunnel that allows connection from Any IP is Edited then the `Done` button was disabled.
- Needed to disable and hide `item` specific binding of the mandatory text fields.
- Verified tunnel creation with peer IP and Any IP after the fix.

NGFW-14983 Hidding and disabling mandatory IPsec tunnel fields conditionally based on Remote Any field

---

directory-connector/src/com/untangle/app/directory_connector/ActiveDirectoryManagerImpl.java

**Issue:** When multiple AD servers are added, authentication fails if the first server is powered off, even if the second server is available.
**Fix:** Removed the return statement to allow the code to check all AD servers before failing authentication. If any server is available, authentication will pass.

NGFW-14982- Fixed Dicrectory Connector AD authentication issue

---

wireguard-vpn/js/view/Tunnels.js
wireguard-vpn/src/com/untangle/app/wireguard_vpn/WireGuardVpnTunnel.java

**Change:** For Wireguard Roaming profiles added an checkbox to make DNS Server and DNS Search Domain optional
`Assign DNS Server` field will be unchecked by default
Static profiles configuration will be as it was before.
If Assign DNS Server is unchecked then config file will ommit DNS line.

Ngfw 14928 wireguard make dns server optional

---

http-casing/src/com/untangle/app/http/HttpUtility.java
http-casing/src/com/untangle/app/http/TlsHandshakeException.java
threat-prevention/src/com/untangle/app/threat-prevention/ThreatPreventionHttpsSniHandler.java
web-filter-base/src/com/untangle/app/web_filter/WebFilterHttpsSniHandler.java

**ISSUE**:
While attempting to extract the SNI (Server Name Indication) hostname, the following exception occurs:
```
Feb  4 21:07:12 localhost app-12: [WebFilterHttpsSniHandler] <TCP113949517415754> WARN  Exception calling extractSNIhostname
Feb 04 21:07:12 localhost app-12:      java.lang.Exception: Packet contains an invalid SSL handshake
Feb 04 21:07:12 localhost app-12:      com.untangle.app.http.HttpUtility.extractSniHostname(HttpUtility.java:78)
```
This results in the session being released, which prevents further processing of domain checks based on the IP and certificate.
**FIX**:
When extracting the SNI hostname for web filtering and threat prevention, we should not immediately release the session when an "invalid packet" exception occurs. Instead, we need to continue checking …

NGFW- 15008: Exception calling extractSNIhostname

---

uvm/api/com/untangle/uvm/util/Constants.java
uvm/js/common/ungrid/Grid.js
uvm/servlets/admin/app/overrides/form/field/VTypes.js
wireguard-vpn/src/com/untangle/app/wireguard_vpn/WireGuardVpnApp.java

**Changes:** 
1. Disabled edit option for tunnels pushed from cloud.
2. Remote Networks are pushed with comma separated values for two or more networks. In NGFW we render and process those values considering line separated values. Modified `setSettings` API to handle this.
3. Resolved import validation bug in `VType` `isSinglePortValid`
Tunnels description starting with `CCTunnel` will be non-editable. 
All values can be seen with inline grid view. User can enable and disable tunnel using inline checkbox.
Tunnel networks will be stored with new line sepearator.

ngfw-15005 Wireguard Tunnels from Cloud should be Non-Editable

---

configuration-backup/hier/usr/share/untangle/bin/configuration-backup-upload-backup.sh

**Changes:**
Modified `getHTTPStatus` method in `configuration-backup-upload-backup.sh` file to support HTTP 1.1 and HTTP 2 responses.
This regex will support all HTTP versions in format `HTTP/{v}` and `HTTP/{v.*}` [v in range (0,9)]
Tested the debug statements in `configuration-backup-upload-backup.sh` using debug mode.
Tested the command with different HTTP version response

ngfw-14891 changed regex to get http status in upload backup script

---

captive-portal/src/com/untangle/app/captive_portal/CaptivePortalSSLEngine.java
ssl-inspector/src/com/untangle/app/ssl_inspector/SslInspectorParserEventHandler.java
uvm/hier/usr/share/untangle/conf/ut-oauth.conf

During debugging the issue, google auth accounts.google.co.<country code> was also seen  it was showing 400 error code, but internet was working. Presently have whitelisted in captive portal and ssl handler. As the country can be variable have added logic to check for startsWith method.
Error Screenshot
Details of the whole issue in
https://awakesecurity.atlassian.net/browse/NGFW-14986

NGFW-14986: Captive Network Assistant for iOS does not work with Google Authentication

---

openvpn/src/com/untangle/app/openvpn/OpenVpnManager.java

**Changes:** 
Writing the IP of any non `publicAddress` DHCP WANs in client config files.
This will be used as a backup if `publicAddress` fails or is wrong.
For interfaces setup as shown below 
the ovpn client configuration file would look like as shown in below screenshot if `publicAddress` equals `firstWanAddress`
else it would consider `firstWanAddress` as a DHCP WAN and add it explicitly in config as shown below.
Same change is applicable for all client configuration files (i.e. `.conf`, `.ovpn`, `.zip` )

ngfw-15044 add secondary dhcp addresses in openvpn config

---

uvm/api/com/untangle/uvm/network/NetworkSettings.java
uvm/impl/com/untangle/uvm/NetworkManagerImpl.java
uvm/servlets/admin/config/network/Interface.js
uvm/servlets/admin/config/network/Main.js
uvm/servlets/admin/config/network/MainController.js
uvm/servlets/admin/config/network/view/Hostname.js

**Requirement**: As an admin managing an NGFW with multiple WANs, I need to choose which WAN is associated with my Dynamic DNS service to ensure that the IP address always resolves to my preferred WAN.
**Implementation**: 
- UI changes to add new field for DDNS  configuration it will show only the WAN interfaces which is currently enabled.
**Validations**:
1- If user try to disable the WAN which is currently used by DDNS config
- User will get an warning in UI 
- If user tried to save the same setting
2- If user try to delete the WAN which is currently used by DDNS config and save the settings below error will be shown
Sync-Setting PR : https://github.com/untangle/sync-settings/pull/2044

NGFW-15042: UI :Option to force dynamic DNS updates to a specific WAN

---

openvpn/src/com/untangle/app/openvpn/OpenVpnManager.java

**Changes:** Refactored code to write remote option in openvpn client config files.
For interfaces setup as shown below
the ovpn client configuration file would look like as shown in below screenshot if publicAddress equals firstWanAddress
else it would consider firstWanAddress as a DHCP WAN and add it explicitly in config as shown below.

ngfw-15053 refactored code to write remote server option in openvpn client config files

---

uvm/impl/com/untangle/uvm/NetworkManagerImpl.java

**ISSUE** : In case of PPPOE we allow blank value as password while upgrading if the the password value set to None getting error while encryptedpassword as it was null at time of upgrade.
**FIX:** Update the code to handle the scenarios for blank password.
**Current Behaviour (17.3)**
When setting PPPOE password as blank, the first call sets pasword as empty strings in both the settings file and chap-secret. On subsequent setSettings calls, the empty fields are set to null in setting file and "None" in chap-secret. This is an existing bug, which will be addressed in a another story.
**Implemetation Behaviour (17.4)**
Same as 17.3 behaviour When setting PPPOE  password as blank, the first call sets password as empty strings in chap-secret and in the settings file v4PPPoEPassword set as …

NGFW-15050- handling the empty password scenario for PPPOE

---

uvm/impl/com/untangle/uvm/NetworkManagerImpl.java

**ISSUE** : In case of PPPOE we allow blank value as password while upgrading if the the password value set to None getting error while encryptedpassword as it was null at time of upgrade.
**FIX:** Update the code to handle the scenarios for blank password.
**Current Behaviour (17.3)**
When setting PPPOE password as blank, the first call sets pasword as empty strings in both the settings file and chap-secret. On subsequent setSettings calls, the empty fields are set to null in setting file and "None" in chap-secret. This is an existing bug, which will be addressed in a another story.
**Implemetation Behaviour (17.4)**
Same as 17.3 behaviour When setting PPPOE  password as blank, the first call sets password as empty strings in chap-secret and in the settings file v4PPPoEPassword set as …

NGFW-15050: Fixed condition to set encrypted password null only for none password

---

captive-portal/hier/usr/share/untangle/web/capture/authpage.html
captive-portal/hier/usr/share/untangle/web/capture/handler.py
captive-portal/hier/usr/share/untangle/web/capture/infopage.html
captive-portal/hier/usr/share/untangle/web/capture/secure.js

As per the issue
https://awakesecurity.atlassian.net/jira/software/c/projects/NGFW/boards/77?selectedIssue=NGFW-15047
IOS devices are unable to connect to captive portal with google auth, as google restricts access with embedded CNA browsers.
As a workaround users will have to navigate in safari or chrome browser in IOS devices,
Instructions will be present captive portal page as follows
Step 1: 
User will be presented with steps if device is IOS and configured auth in captive portal is google signon
Step2:
captive portal link which can be copied and opened on new browser
Step3
User should presented normal captive portal and redirected to google signon
This change will be only for IOS devices for other devices normal captive portal should be shown.
Screenshots added in Jira issue link …

NGFW-15047: iOS CNA browser cannot use Google oAuth

---

debian/control
license/src/com/untangle/app/license/LicenseManagerImpl.java

Removed unwanted code for requestTrail and removing sbl license form license list.
**Expected license behaviour:** 
**On Previous version (17.3) :** 
- If user have any app spam-blocker or spam-blocker-lite, they should not get any error related to licnese.
**After Upgrade on 17.4:** 
- If user have spam-blocker-lite app in 17.3 then after upgrade this app will be removed and in license only the spam-blocker licnese should be visible.
- If user have spam-blocker app then after upgrade this app will use sapmassaian service instead of untangle-spamcatd and in license only the spam-blocker licnese should be visible.

NGFW-15055: License changes for SBL removal

---

wireguard-vpn/js/Main.js
wireguard-vpn/js/MainController.js
wireguard-vpn/js/view/Settings.js
wireguard-vpn/js/view/Status.js
wireguard-vpn/js/view/Tunnels.js
wireguard-vpn/src/com/untangle/app/wireguard_vpn/WireGuardVpnApp.java
wireguard-vpn/src/com/untangle/app/wireguard_vpn/WireGuardVpnNetworkProfile.java
wireguard-vpn/src/com/untangle/app/wireguard_vpn/WireGuardVpnSettings.java
wireguard-vpn/src/com/untangle/app/wireguard_vpn/WireGuardVpnTunnel.java

Support for Wireguard VPN Local Networks Profile:
**Changes:**
1. Status Page: - Remove **Local Service Information** clipboard from the page. As Local networks will be different for each tunnel.
2. Settings Page: - 
- Changed **Local Networks** field to **Local Network Profiles**
This field will contain Network Profiles with multiple comma separated Local Networks in CIDR format.
First profile will always be `Full Tunnel - 0.0.0.0/0`. It will be non editable and non deletable.
Second profile will be `Default` profile. For fresh install default profile will have all local LAN networks from networks settings. On upgrade old local networks will be added to Default profile.
User will be able to Add/Edit/Delete the network profiles.
- Validations: 
Profile Name: Duplicate profile names won't …

Ngfw 15088 wireguard routed network profiles

---

uvm/js/common/util/Util.js
uvm/servlets/admin/sass/base.scss
web-filter/js/Main.js
web-filter/js/MainController.js
web-filter/js/view/BlockSites.js
web-filter/js/view/PassSites.js

As will be as below:
- Once a site is saved as Global, the user will not be able to modify the Global field and Global record will be highlighted.
>![Screenshot from 2025-04-23 19-36-38](https://github.com/user-attachments/assets/8c4e972e-82e3-4dd0-af08-86940fb82337)
- The Global checkbox will be visible only in the editor fields during the Add operation.
> **PassSIte:**
> ![Screenshot from 2025-04-23 18-39-42](https://github.com/user-attachments/assets/352784dd-1500-4804-9489-27fc0d6d8623)
> **BlockSite:**
> ![image](https://github.com/user-attachments/assets/a54c9c9d-1997-48d0-93d6-d2c1d6bf3cb0)
- For edit operation editorField, global field is not visible.
> **PassSite:**
> ![Screenshot from 2025-04-23 18-42-58](https://github.com/user-attachments/assets/d4935009-767c-49ed-86fe-67d030dd …

NGFW-15092: UI changes for Webfilter Global Pass/Block Sites

---

policy-manager/hier/usr/lib/python3/dist-packages/tests/test_policy_manager.py
uvm/hier/usr/lib/python3/dist-packages/tests/common.py
uvm/hier/usr/lib/python3/dist-packages/tests/global_functions.py
web-filter-base/hier/usr/lib/python3/dist-packages/tests/test_web_filter_base.py
web-filter/hier/usr/lib/python3/dist-packages/tests/test_web_filter.py

Added test cases specific to the web-filter Global block/pass sites rule:
1 - Verify addition and removal of Global block/pass sites. 
> test_202_url_filtering_global_vs_instance_specific_rules_reflection
2- Verify that a global block rule applies only when a corresponding per-instance pass rule is NOT present.
> test_203_url_filtering_respects_pass_and_block_rules_per_ip
3- Verify that a globally flagged (not blocked) URL logs a flagged event only for the instance which does NOT have an explicit pass rule. The instance with a local pass rule for the same URL should NOT log a flagged event.
> test_204_flagged_logs_only_without_pass
4- Verifies that during concurrent setSettings calls across multiple web filter instances, the global settings persist correctly and the last completed update …

Ngfw -15103/15120 :  ATS tests to verify Web-Filter Global Block/Pass URL site support

---

uvm/api/com/untangle/uvm/CloudApp.java
uvm/api/com/untangle/uvm/GoogleCloudApp.java
uvm/api/com/untangle/uvm/GoogleSettings.java
uvm/api/com/untangle/uvm/util/Constants.java
uvm/hier/usr/share/untangle/bin/ut-google-drive-helper.sh
uvm/impl/com/untangle/uvm/GoogleManagerImpl.java
uvm/impl/com/untangle/uvm/UriManagerImpl.java
uvm/servlets/admin/config/administration/MainController.js

- `drive` cli package is no longer used. As a result, retrieving/refreshing access token, handling authorization and authentication has to be done by untangle-vm using google REST APIs.
- Migrate older google drive settings to newer version (v1) by also getting a new access token.
settings before upgrade
```
[root @ arista] ~ # cat /usr/share/untangle/settings/untangle-vm/google.js
{
"driveRefreshToken": "<REFRESH_TOKEN>",
"googleDriveRootDirectory": "New NGFW Backups",
"javaClass": "com.untangle.uvm.GoogleSettings"
}
```
after upgrade, (same refresh token is retained in encrypted form, retrieved new access token, stored in encrypted form, and kept directory selection as is.
```
{
"accessTokenExpiresIn": 3599,
"encryptedDriveAccessToken": …
```

NGFW-15107 Google drive oauth2 implementation using REST APIs

---

ipsec-vpn/hier/usr/lib/python3/dist-packages/tests/test_ipsec_vpn.py

The configuration only allows local server clients to access the remote client(i.e from 10.112.56.15/32). However, the command is being executed directly from the NGFW server, (as it first ssh the client 192.168.235.83 and then run the nc  command ) which results in the following error as show in **network unreachable**.
To resolve this, updated both the TC configuration and the IPSec configuration on the 10.112.56.96 server to properly handle communication with the ats-bridged server.

ngfw-15095 - Fixed test_025_VerifyIPsecBypass

---

configuration-backup/src/com/untangle/app/configuration_backup/ConfigurationBackupApp.java
configuration-backup/src/com/untangle/app/configuration_backup/ConfigurationBackupSettings.java
reports/src/com/untangle/app/reports/ReportsApp.java
reports/src/com/untangle/app/reports/ReportsSettings.java
uvm/api/com/untangle/uvm/GoogleManager.java
uvm/api/com/untangle/uvm/GoogleSettings.java
uvm/impl/com/untangle/uvm/GoogleManagerImpl.java
uvm/impl/com/untangle/uvm/UriManagerImpl.java
uvm/servlets/admin/config/administration/MainController.js

- Folder selection from Google tab using Picker now also gets the folderId of the selected folder.
- Added methods to, resolve the folderId of the input directory under a specified parent folder. Creates the folder if not present (controlled by `createFolder` flag).
- During upgrades, google manager sets the folderId of the root folder (selected from Picker) only if folder name is available and drive is configured.
- For Reports and Configuration Apps, upgrades set folderId of the respective app folder names. Looks for folder under root directory set in google settings.
- App setSettings fetches the folderId of the input folder name.

Ngfw 15107 Resolving google directory with its folderId

---

uvm/hier/usr/lib/python3/dist-packages/tests/test_syslog.py

Calling the syslog setSettings method caused the rsyslog status to change to 'failed' because a restart was triggered before the first execution completed. As a result, no logs were generated afterward. The issue was fixed by checking the rsyslog status and restarting the service if it was in a failed state. This issue occurs only in test cases, as multiple setSettings calls are made in rapid succession without any delay between them.
**BEFORE :**
**AFTER:**

ngfw-15134 - Fixed threat-prevention : test_551_https_with_sni_packet_split

---

uvm/js/common/util/Util.js
wireguard-vpn/js/view/Settings.js

**ISSUE:** Wireguard VPN server Peer IP address pool Network space is manually able assign as the Public network space.
**FIXED:** Added validation so peer IP address Pool network space should only allow Private IP network range.
- **Network space should be in valid CIDR format**
-  **Network space with conflicting network should give any error**
- **Public network should give error**
- **Valid network space should not give any error**

ngfw-13480 : Added validation to restrict public address in peer address

---

configuration-backup/js/view/GoogleConnector.js
configuration-backup/src/com/untangle/app/configuration_backup/ConfigurationBackupApp.java
reports/js/view/Data.js
uvm/api/com/untangle/uvm/util/Pulse.java
uvm/hier/usr/lib/python3/dist-packages/tests/test_uvm.py
uvm/impl/com/untangle/uvm/GoogleManagerImpl.java
uvm/servlets/admin/config/administration/view/Google.js

- Root google drive directory settings (Administration -> Google) is now optional.
- This root google drive directory can be manually entered as opposed to be only set via Select Directory option using Picker functionality.
- If set manually, user no need to create this root directory on their google drive. NGFW will create this directory.
- If not set manually, users can still select an existing directory from their drive as it is currently supported.
- Generating specific event for 401 token invalid error.
- If root google drive directory is kept empty then app specific directories (configuration backup and reports) will get created at root level on google drive.
- ATS test case to verify client_id and redirect_uri from credentials.json against the API that returns google authorization …

Ngfw 15107 Google drive root directory is now optional

---

openvpn/hier/usr/lib/python3/dist-packages/tests/test_openvpn.py
openvpn/hier/usr/share/untangle/bin/openvpn-import-config
openvpn/servlets/openvpn/src/com/untangle/app/openvpn/servlet/UploadConfig.java
uvm/api/com/untangle/uvm/util/Constants.java

This PR contains the implementation logic to support openvpn site-to-site inline configuration.
During grooming for [NGFW-13265](https://awakesecurity.atlassian.net/browse/NGFW-13265), we aligned on continuing support for .zip, .ovpn, and .onc file downloads in the release that introduces inline import support.
As per that discussion, we will:
- Retain .zip download and upload support in version 17.5
- Will have .ovpn  download and upload support for all upcoming versions
- Will have .onc download support
Also write basic unit test case to cover site-to-site tunnle creation through inline config file. 
**NOTE : Skipping new added test for ATS servers for now as inline file needs to be place on test server.**
[NGFW-13265]: https://awakesecurity.atlassian.net/browse/NGFW-13265?atlOrigin=eyJp …

 ngfw-15106 : Openvpn site-to-site connection Inline Import Implementation

---

buildtools/jars.rb
downloads/Makefile
uvm/api/com/untangle/uvm/util/ObjectMatcher.java
uvm/impl/com/untangle/uvm/SessionMonitorImpl.java
uvm/impl/com/untangle/uvm/SettingsManagerImpl.java

We need to set marhsalling mode inorder for jabsorb to decide which mode of marshalling has to be used to serialize objects.
For ngfw_src, except for the API requests, we need to ensure rest of the serialization like reading of settings file or command output has to be done with JABSORB mode since we are not changing the structure of these.
Setting of marshalling mode for APIs has to be handled from jabsorb library.

NGWF-15206 Setting marshalling mode before calling jabsorb library

---

uvm/api/com/untangle/uvm/network/InterfaceSettings.java
uvm/api/com/untangle/uvm/network/generic/InterfaceSettingsGeneric.java
uvm/api/com/untangle/uvm/network/generic/InterfaceStatusGeneric.java
uvm/impl/com/untangle/uvm/NetworkManagerImpl.java

As a part of vue migration we are creating new API's for vue Application.
Modified InterfaceSettingsGeneric and InterfaceStatusGeneric classes to match vuntangle conventions.
`vuntangle` needs **enabled** field in `interfaceSettings` object to populated Status (connected/disconnected, offline/online)
For now settings all interfaceSettings.enabled = true. With VPN changes the value will be mapped to respective enabled field.
interface status object should also contain **wan** field for same purpose.
**duplex** value should be either `full`, `half` if UNKNOWN settings it to 'unknown'.

ngfw-15211 enabled, wan and duplex field changes

---

openvpn/src/com/untangle/app/openvpn/OpenVpnAppImpl.java
openvpn/src/com/untangle/app/openvpn/OpenVpnRemoteServer.java
uvm/api/com/untangle/uvm/util/Constants.java

Currently, client configuration is handled by the uploadConfig servlet. However, with the migration to Vue, we are moving away from relying on the servlet and file object input.
Now, the configuration payload for the client will be received in the following format:
> 
> {
>   "enabled": true,
>   "name": "",
>   "authUserPass": false,
>   "authUsername": "",
>   "authPassword": "",
>   "openvpnConfFile": {
>     "contents": "",
>     "encoding": "base64"
>   }
> }
This means we will receive the OpenVPN configuration file as a base64-encoded string along with its encoding format. We need to decode the contents based on the provided encoding and use the resulting data to configure the client.
DEMO VIDEO: showcasing before and after behaviour of openvpn client configuration
[Screencast from …

NGFW-15225: OpenVPN : Updated remoteServer attribute and configuration logic as per vue migration

---

reports/src/com/untangle/app/reports/EventWriterImpl.java
reports/src/com/untangle/app/reports/ReportsManagerImpl.java

On one of the prod box the reports app was failing after few days of restart.
v17.3.1
Added new logs giving us info about writer thread state and input queue length along with other logs at suspicious code.

ngfw-15214 Added logs to know the eventwriter thread state

---

uvm/api/com/untangle/uvm/SystemSettings.java
uvm/api/com/untangle/uvm/generic/SystemSettingsGeneric.java
uvm/impl/com/untangle/uvm/SystemManagerImpl.java

We have Hostname and Services tab settings in the ExtJs at `Config -> Network`.
In Vue UI those settings will be shown at `System -> Settings` Page.
To achieve above change implemented below solution.
1. Created `SystemSettingsGeneric` POJO for Vue v2 API's 
2. Created `getSystemSettingsV2` and `setSystemSettingsV2` API's for data transformation.
These API's use Network Settings to get and persist data in back-end for Hostname and Services Settings.

ngfw-15261 created get and set SystemSettingsV2 API's

---

uvm/api/com/untangle/uvm/network/InterfaceSettings.java
uvm/impl/com/untangle/uvm/NetworkManagerImpl.java
uvm/impl/com/untangle/uvm/SystemManagerImpl.java
uvm/servlets/admin/app/view/main/IframePanel.js

In set settings v2 API's we were directly modifying the manager class settings object. 
In case of sanity failure this would cause issue of data mismatch in `network.js` and JVM object.
To handle this we need to clone original object apply transformations on cloned object and then pass it in set settings as new settings.
Other Changes:
1. Refactored Imports 
2. Using `V6ConfigType` for static variable instead of class variable `v6ConfigType`
3. Removed unnecessary console.log

ngfw-15261 clone original settings to transform

---

uvm/api/com/untangle/uvm/app/DayOfWeekMatcher.java
uvm/api/com/untangle/uvm/network/InterfaceSettings.java
uvm/impl/com/untangle/uvm/NetworkManagerImpl.java
uvm/impl/com/untangle/uvm/SystemManagerImpl.java

- Added interface specific `getinterfaceStatusV2` API which accepts device as param and returns status response. 
This API is needed on interface edit page. Unnecessarily we had to fetch all intf status and hence, increased response time.
- For `SerializationUtils.clone` we need all nested objects to implement `java.io.Serializable`. Added same for `DayOfWeekMatcher` and `InterfaceAlias` classes.
- Changed `networkSettings` reference with `clonedNetworkSettings` reference for transformation method in `setSystemSettingsV2`

Ngfw 15261 create getinterfaceStatusV2

---

uvm/api/com/untangle/uvm/network/InterfaceSettings.java
uvm/api/com/untangle/uvm/network/NetworkSettings.java
uvm/api/com/untangle/uvm/network/StaticRoute.java
uvm/api/com/untangle/uvm/network/generic/InterfaceSettingsGeneric.java
uvm/api/com/untangle/uvm/network/generic/NetworkSettingsGeneric.java
uvm/api/com/untangle/uvm/network/generic/StaticRouteGeneric.java

- Added transformation logic for Static Routes in `getNetworkSettingsV2` and `setNetworkSettingsV2` API's
- Removed v1 model `dhcpEnabled` (redundant) field mapping logic

ngfw-15293 transformation for static routes

---

uvm/js/common/util/_Map.js

**Changes:**
1. Changed **Protocol** column filter type to default (string filter). As field display value is of type string, numeric filter won't work.
-----------------------------------------------------------
2. Changed **Elapsed** field type to string as we get string value. Removed unnecessary converter (timestamp to date. Time Elapsed can't be expressed as Date value). Assigning default filter (string filter).

Ngfw 15333 reports protocol filter issue

---

uvm/api/com/untangle/uvm/SystemSettings.java
uvm/api/com/untangle/uvm/generic/SystemSettingsGeneric.java
uvm/impl/com/untangle/uvm/SystemManagerImpl.java

During testing of the TimeZone Vue migration, a bug was identified where changing the timezone via ETM does not update the system.js settings properly. This occurs because the ETM directly calls the timedatectl command to set the timezone, bypassing the usual update mechanisms. As a result, there is a data discrepancy in the displayed timezone information. hence the UI shows outdated timezone data after changes through ETM.
Fixed the issue via refering single file /etc/timezone for timezone settings.

ngfw-15345: Fixed Timezone data discrepancy issue

---

uvm/js/common/util/Util.js
uvm/servlets/admin/config/network/Interface.js

This PR updates IP address validation logic to allow /31 subnets.
According to [RFC 3021](https://datatracker.ietf.org/doc/html/rfc3021), both IPs in a /31 subnet are usable, eliminating the need for traditional broadcast and network address validation.
**Changes:**
Skipped broadcast and network address checks for /31 subnets
Ensured both IPs in /31 are considered valid for static configuration
**Testing:**
- Navigate to Config → Network.
- Click Add VLAN.
- Enter the required details.
- For the static IPv4 address, use a subnet of /31.
- Set the DHCP range according to the given /31 IP address.
- Verify that both IPs in the /31 subnet are accepted and no UI validation errors are shown.
**Functional Testing:**
- Set up a point-to-point link using a /31 subnet between two devices or …

ngfw-15338: Allow 31 Subnet
